// DICOMDIRProfileTables.swift
// DICOMKit
//
// GENERATED by Scripts/generate_dicomdir_profile_rules.py from DICOM PS3.11 2026a - Media Storage Application Profiles
// and DICOM PS3.4 2026a - Service Class Specifications. Do not hand-edit: fix the generator and regenerate.
//
// NEMA-verified: 2026a, checked 2026-10-01 — every non-Basic-Directory row of PS3.11 2026a Tables A.3-1 (1), B.3-1 (5), C.3-1 (6), D.3-1 (1), E.3-1 (10), G.3-1 (1), H.3-1 (6), I.3-1 (1), J.3-1 (6), K.3-1 (4), L.3-1 (1), L.3-2 (2), M.3-1 (10), N.3-1 (3) (57 rows) and the 9 SOP Classes of PS3.4 2026a Table GG.3-1, generated from the DocBook; `generate_dicomdir_profile_rules.py --check` re-verifies it.
// Image attribute rows of Tables A.3-3, B.3-3, B.3-4, E.3-3, E.3-4, E.3-5, E.3-6, K.3-3, L.4-1, K.3-4, L.4-2 (47 rows) and the 5 Photometric Interpretation rows of Table C.3-2 copied verbatim.

import DICOMCore

extension DICOMDIRProfileRules {
    /// One row of a PS3.11 "SOP Classes and Transfer Syntaxes" table (the Basic Directory
    /// row is left out: it describes the DICOMDIR, not the instances it references).
    struct TableRow: Sendable, Equatable {
        /// Information Object Definition column, verbatim.
        let iod: String
        /// SOP Class UID; nil for "Composite IODs for which a Media Storage SOP Class is defined in PS3.4".
        let sopClassUID: String?
        /// The row is for "Multi-frame Composite IODs" only.
        let multiFrameOnly: Bool
        /// Transfer Syntax UID; nil for "Defined in Conformance Statement".
        let transferSyntaxUID: String?
        /// FSC Requirement column, verbatim.
        let fsc: String
        /// FSR Requirement column, verbatim (carries the "-JPEG / J2K profiles" qualifiers).
        let fsr: String
    }

    /// PS3.11 2026a tables, keyed by table label.
    static let tables: [String: [TableRow]] = [
        "A.3-1": [
            TableRow(iod: "X-Ray Angiographic Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.12.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.70", fsc: "Mandatory", fsr: "Mandatory"),
        ],
        "B.3-1": [
            TableRow(iod: "X-Ray Angiographic Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.12.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.70", fsc: "Mandatory", fsr: "Mandatory"),
            TableRow(iod: "X-Ray Angiographic Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.12.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.50", fsc: "Optional for DVD; Disallowed for CD", fsr: "Mandatory for DVD; Disallowed for CD"),
            TableRow(iod: "X-Ray Angiographic Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.12.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.51", fsc: "Optional for DVD; Disallowed for CD", fsr: "Mandatory for DVD; Disallowed for CD"),
            TableRow(iod: "Secondary Capture Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.7", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Mandatory"),
            TableRow(iod: "Grayscale Softcopy Presentation State", sopClassUID: "1.2.840.10008.5.1.4.1.1.11.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Optional"),
        ],
        "C.3-1": [
            TableRow(iod: "Ultrasound Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.6.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Mandatory", fsr: "Mandatory"),
            TableRow(iod: "Ultrasound Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.6.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.5", fsc: "Mandatory", fsr: "Mandatory"),
            TableRow(iod: "Ultrasound Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.6.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.50", fsc: "Mandatory", fsr: "Mandatory"),
            TableRow(iod: "Ultrasound Multi-frame Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.3.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Mandatory", fsr: "Mandatory"),
            TableRow(iod: "Ultrasound Multi-frame Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.3.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.5", fsc: "Mandatory", fsr: "Mandatory"),
            TableRow(iod: "Ultrasound Multi-frame Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.3.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.50", fsc: "Mandatory", fsr: "Mandatory"),
        ],
        "D.3-1": [
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Defined in Conformance Statement", fsr: "Defined in Conformance Statement"),
        ],
        "E.3-1": [
            TableRow(iod: "CT Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.2", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.70", fsc: "Optional", fsr: "Mandatory"),
            TableRow(iod: "CT Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.2", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Mandatory"),
            TableRow(iod: "MR Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.4", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.70", fsc: "Optional", fsr: "Mandatory"),
            TableRow(iod: "MR Image", sopClassUID: "1.2.840.10008.5.1.4.1.1.4", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Mandatory"),
            TableRow(iod: "Secondary Capture Image (Grayscale)", sopClassUID: "1.2.840.10008.5.1.4.1.1.7", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.70", fsc: "Optional", fsr: "Mandatory"),
            TableRow(iod: "Secondary Capture Image (Grayscale)", sopClassUID: "1.2.840.10008.5.1.4.1.1.7", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Mandatory"),
            TableRow(iod: "Secondary Capture Image (Palette Color)", sopClassUID: "1.2.840.10008.5.1.4.1.1.7", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.70", fsc: "Optional", fsr: "Optional"),
            TableRow(iod: "Secondary Capture Image (Palette Color)", sopClassUID: "1.2.840.10008.5.1.4.1.1.7", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Optional"),
            TableRow(iod: "Grayscale Softcopy Presentation State", sopClassUID: "1.2.840.10008.5.1.4.1.1.11.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Optional"),
            TableRow(iod: "X-Ray Radiation Dose SR", sopClassUID: "1.2.840.10008.5.1.4.1.1.88.67", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Optional"),
        ],
        "G.3-1": [
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: nil, fsc: "Defined in Conformance Statement", fsr: "Defined in Conformance Statement"),
        ],
        "H.3-1": [
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Defined in Conformance Statement", fsr: "Mandatory for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.70", fsc: "Defined in Conformance Statement", fsr: "Mandatory for -JPEG profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.50", fsc: "Defined in Conformance Statement", fsr: "Mandatory for -JPEG profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.51", fsc: "Defined in Conformance Statement", fsr: "Mandatory for -JPEG profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.90", fsc: "Defined in Conformance Statement", fsr: "Mandatory for -J2K profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.91", fsc: "Defined in Conformance Statement", fsr: "Mandatory for -J2K profiles for all SOP Classes defined in Conformance Statement"),
        ],
        "I.3-1": [
            TableRow(iod: "Multi-frame Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: true, transferSyntaxUID: "1.2.840.10008.1.2.4.100", fsc: "Defined in Conformance Statement", fsr: "Mandatory for all SOP Classes defined in Conformance Statement"),
        ],
        "J.3-1": [
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Defined in Conformance Statement", fsr: "Mandatory for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.70", fsc: "Defined in Conformance Statement", fsr: "Mandatory for JPEG profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.50", fsc: "Defined in Conformance Statement", fsr: "Mandatory for JPEG profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.51", fsc: "Defined in Conformance Statement", fsr: "Mandatory for JPEG profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.90", fsc: "Defined in Conformance Statement", fsr: "Mandatory for J2K profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.91", fsc: "Defined in Conformance Statement", fsr: "Mandatory for J2K profiles for all SOP Classes defined in Conformance Statement"),
        ],
        "K.3-1": [
            TableRow(iod: "Digital Intra-oral X-Ray Image Storage - For Presentation", sopClassUID: "1.2.840.10008.5.1.4.1.1.1.3", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Mandatory"),
            TableRow(iod: "Digital X-Ray Image Storage - For Presentation", sopClassUID: "1.2.840.10008.5.1.4.1.1.1.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Mandatory"),
            TableRow(iod: "Basic Structured Display Storage", sopClassUID: "1.2.840.10008.5.1.4.1.1.131", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Optional"),
            TableRow(iod: "Grayscale Softcopy Presentation State", sopClassUID: "1.2.840.10008.5.1.4.1.1.11.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Optional"),
        ],
        "L.3-1": [
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: nil, fsc: "Defined in Conformance Statement", fsr: "Defined in Conformance Statement"),
        ],
        "L.3-2": [
            TableRow(iod: "Digital Intra-oral X-Ray Image Storage - For Presentation", sopClassUID: "1.2.840.10008.5.1.4.1.1.1.3", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Mandatory"),
            TableRow(iod: "Digital X-Ray Image Storage - For Presentation", sopClassUID: "1.2.840.10008.5.1.4.1.1.1.1", multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Optional", fsr: "Mandatory"),
        ],
        "M.3-1": [
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.1", fsc: "Defined in Conformance Statement", fsr: "Mandatory for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.70", fsc: "Defined in Conformance Statement", fsr: "Mandatory for JPEG profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.50", fsc: "Defined in Conformance Statement", fsr: "Mandatory for JPEG profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.51", fsc: "Defined in Conformance Statement", fsr: "Mandatory for JPEG profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.90", fsc: "Defined in Conformance Statement", fsr: "Mandatory for J2K profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: false, transferSyntaxUID: "1.2.840.10008.1.2.4.91", fsc: "Defined in Conformance Statement", fsr: "Mandatory for J2K profiles for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Multi-frame Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: true, transferSyntaxUID: "1.2.840.10008.1.2.4.100", fsc: "Defined in Conformance Statement", fsr: "Mandatory for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Multi-frame Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: true, transferSyntaxUID: "1.2.840.10008.1.2.4.101", fsc: "Defined in Conformance Statement", fsr: "Mandatory for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Multi-frame Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: true, transferSyntaxUID: "1.2.840.10008.1.2.4.102", fsc: "Defined in Conformance Statement", fsr: "Mandatory for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Multi-frame Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: true, transferSyntaxUID: "1.2.840.10008.1.2.4.103", fsc: "Defined in Conformance Statement", fsr: "Mandatory for all SOP Classes defined in Conformance Statement"),
        ],
        "N.3-1": [
            TableRow(iod: "Multi-frame Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: true, transferSyntaxUID: "1.2.840.10008.1.2.4.104", fsc: "Defined in Conformance Statement", fsr: "Mandatory for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Multi-frame Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: true, transferSyntaxUID: "1.2.840.10008.1.2.4.105", fsc: "Defined in Conformance Statement", fsr: "Mandatory for all SOP Classes defined in Conformance Statement"),
            TableRow(iod: "Multi-frame Composite IODs for which a Media Storage SOP Class is defined in PS3.4", sopClassUID: nil, multiFrameOnly: true, transferSyntaxUID: "1.2.840.10008.1.2.4.106", fsc: "Defined in Conformance Statement", fsr: "Mandatory for all SOP Classes defined in Conformance Statement"),
        ],
    ]

    /// PS3.11 2026a "Required Image Attribute Values" tables: Attribute, Tag, Value (verbatim).
    static let imageAttributeValueTables: [String: [(name: String, tag: Tag, value: String)]] = [
        "A.3-3": [
            ("Modality", Tag(group: 0x0008, element: 0x0060), "XA"),
            ("Rows", Tag(group: 0x0028, element: 0x0010), "512 (see below)"),
            ("Columns", Tag(group: 0x0028, element: 0x0011), "512 (see below)"),
            ("Bits Allocated", Tag(group: 0x0028, element: 0x0100), "8"),
            ("Bits Stored", Tag(group: 0x0028, element: 0x0101), "8"),
        ],
        "B.3-3": [
            ("Modality", Tag(group: 0x0008, element: 0x0060), "XA"),
            ("Rows", Tag(group: 0x0028, element: 0x0010), "up to 1024 (see below)"),
            ("Columns", Tag(group: 0x0028, element: 0x0011), "up to 1024 (see below)"),
            ("Bits Stored", Tag(group: 0x0028, element: 0x0101), "8, 10, and 12 bits only"),
        ],
        "B.3-4": [
            ("Rows", Tag(group: 0x0028, element: 0x0010), "up to 1024 (see below)"),
            ("Columns", Tag(group: 0x0028, element: 0x0011), "up to 1024 (see below)"),
            ("Samples per Pixel", Tag(group: 0x0028, element: 0x0002), "1"),
            ("Photometric Interpretation", Tag(group: 0x0028, element: 0x0004), "MONOCHROME2"),
            ("Bits Allocated", Tag(group: 0x0028, element: 0x0100), "8 bits only"),
            ("Bits Stored", Tag(group: 0x0028, element: 0x0101), "8 bits only"),
            ("High Bit", Tag(group: 0x0028, element: 0x0102), "7"),
            ("Pixel Representation", Tag(group: 0x0028, element: 0x0103), "0000H (unsigned)"),
        ],
        "E.3-3": [
            ("Modality", Tag(group: 0x0008, element: 0x0060), "CT"),
            ("Photometric Interpretation", Tag(group: 0x0028, element: 0x0004), "MONOCHROME2"),
        ],
        "E.3-4": [
            ("Modality", Tag(group: 0x0008, element: 0x0060), "MR"),
            ("Photometric Interpretation", Tag(group: 0x0028, element: 0x0004), "MONOCHROME2"),
            ("Bits Stored", Tag(group: 0x0028, element: 0x0101), "8, 12 to 16"),
            ("High Bit", Tag(group: 0x0028, element: 0x0102), "Bits Stored (0028,0101) - 1"),
        ],
        "E.3-5": [
            ("Samples Per Pixel", Tag(group: 0x0028, element: 0x0002), "1"),
            ("Photometric Interpretation", Tag(group: 0x0028, element: 0x0004), "MONOCHROME2"),
            ("Bits Allocated", Tag(group: 0x0028, element: 0x0100), "8 or 16"),
            ("Bits Stored", Tag(group: 0x0028, element: 0x0101), "Bits Allocated (0028,0100)"),
            ("High Bit", Tag(group: 0x0028, element: 0x0102), "Bits Stored (0028,0101) - 1"),
        ],
        "E.3-6": [
            ("Samples Per Pixel", Tag(group: 0x0028, element: 0x0002), "1"),
            ("Photometric Interpretation", Tag(group: 0x0028, element: 0x0004), "PALETTE COLOR"),
            ("Bits Allocated", Tag(group: 0x0028, element: 0x0100), "8"),
            ("Bits Stored", Tag(group: 0x0028, element: 0x0101), "8"),
            ("High Bit", Tag(group: 0x0028, element: 0x0102), "7"),
        ],
        "K.3-3": [
            ("Bits Allocated", Tag(group: 0x0028, element: 0x0100), "If Bits Stored (0028,0101) is 8, then 8; otherwise 16."),
            ("Bits Stored", Tag(group: 0x0028, element: 0x0101), "8, 10, 12 or 16"),
        ],
        "L.4-1": [
            ("Bits Allocated", Tag(group: 0x0028, element: 0x0100), "If Bits Stored (0028,0101) is 8, then 8; otherwise 16."),
            ("Bits Stored", Tag(group: 0x0028, element: 0x0101), "8, 10, 12 or 16"),
        ],
    ]

    /// PS3.11 2026a "Required Image Attribute Types" tables: Attribute, Tag, Type.
    static let imageAttributeTypeTables: [String: [(name: String, tag: Tag, type: String)]] = [
        "K.3-4": [
            ("Institution Name", Tag(group: 0x0008, element: 0x0080), "2"),
            ("Manufacturer's Model Name", Tag(group: 0x0008, element: 0x1090), "2"),
            ("Detector ID", Tag(group: 0x0018, element: 0x700A), "2"),
            ("Detector Manufacturer Name", Tag(group: 0x0018, element: 0x702A), "2"),
            ("Detector Manufacturer's Model Name", Tag(group: 0x0018, element: 0x702B), "2"),
        ],
        "L.4-2": [
            ("Institution Name", Tag(group: 0x0008, element: 0x0080), "2"),
            ("Manufacturer's Model Name", Tag(group: 0x0008, element: 0x1090), "2"),
            ("Detector ID", Tag(group: 0x0018, element: 0x700A), "2"),
            ("Detector Manufacturer Name", Tag(group: 0x0018, element: 0x702A), "2"),
            ("Detector Manufacturer's Model Name", Tag(group: 0x0018, element: 0x702B), "2"),
        ],
    ]

    /// PS3.11 2026a Table C.3-2: Photometric Interpretation -> Transfer Syntax UIDs.
    static let ultrasoundPhotometricTransferSyntaxes: [String: [String]] = [
        "MONOCHROME2": ["1.2.840.10008.1.2.1", "1.2.840.10008.1.2.5"],
        "RGB": ["1.2.840.10008.1.2.1", "1.2.840.10008.1.2.5"],
        "PALETTE COLOR": ["1.2.840.10008.1.2.1", "1.2.840.10008.1.2.5"],
        "YBR_FULL": ["1.2.840.10008.1.2.5"],
        "YBR_FULL_422": ["1.2.840.10008.1.2.1", "1.2.840.10008.1.2.4.50"],
    ]

    /// PS3.4 2026a Table GG.3-1 (Non-Patient Object Storage): Media Storage SOP Classes per PS3.4 I.4.
    static let nonPatientStorageUIDs: Set<String> = [
        "1.2.840.10008.5.1.4.38.1",  // Hanging Protocol Storage
        "1.2.840.10008.5.1.4.39.1",  // Color Palette Storage
        "1.2.840.10008.5.1.4.43.1",  // Generic Implant Template Storage
        "1.2.840.10008.5.1.4.44.1",  // Implant Assembly Template Storage
        "1.2.840.10008.5.1.4.45.1",  // Implant Template Group Storage
        "1.2.840.10008.5.1.4.1.1.200.1",  // CT Defined Procedure Protocol Storage
        "1.2.840.10008.5.1.4.1.1.200.3",  // Protocol Approval Storage
        "1.2.840.10008.5.1.4.1.1.200.7",  // XA Defined Procedure Protocol Storage
        "1.2.840.10008.5.1.4.1.1.201.1",  // Inventory Storage
    ]
}
