name: DICOMToolbox
options:
  bundleIdPrefix: com.rasterlab
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

packages:
  DICOMKit:
    path: ..

targets:
  DICOMToolbox:
    type: application
    platform: macOS
    sources:
      - App
      - Models
      - ViewModels
      - Views
      - Services
    dependencies:
      - package: DICOMKit
        product: DICOMKit
      - package: DICOMKit
        product: DICOMCore
      - package: DICOMKit
        product: DICOMNetwork
      - package: DICOMKit
        product: DICOMWeb
    settings:
      PRODUCT_NAME: DICOMToolbox
      PRODUCT_BUNDLE_IDENTIFIER: com.rasterlab.dicomtoolbox
      INFOPLIST_FILE: Info.plist
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      SWIFT_VERSION: "5.9"
      ENABLE_PREVIEWS: YES
    scheme:
      testTargets:
        - DICOMToolboxTests

  DICOMToolboxTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
    dependencies:
      - target: DICOMToolbox
      - package: DICOMKit
        product: DICOMKit
    settings:
      PRODUCT_NAME: DICOMToolboxTests
      PRODUCT_BUNDLE_IDENTIFIER: com.rasterlab.dicomtoolbox.tests
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      SWIFT_VERSION: "5.9"
