name: DICOMViewer
options:
  bundleIdPrefix: com.dicomkit.viewer
  deploymentTarget:
    visionOS: "1.0"
  developmentLanguage: en
  xcodeVersion: "15.2"

packages:
  DICOMKit:
    path: ../

settings:
  base:
    PRODUCT_NAME: DICOMViewer
    SWIFT_VERSION: "6.0"
    ENABLE_PREVIEWS: true
    DEVELOPMENT_ASSET_PATHS: ""
    IPHONEOS_DEPLOYMENT_TARGET: "1.0"
    TARGETED_DEVICE_FAMILY: "7"  # visionOS
    SUPPORTS_MACCATALYST: false
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    MARKETING_VERSION: "1.0.14"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: true
    CLANG_ENABLE_CODE_COVERAGE: true
    SWIFT_STRICT_CONCURRENCY: complete
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      SWIFT_COMPILATION_MODE: incremental
      ENABLE_TESTABILITY: true
    Release:
      SWIFT_OPTIMIZATION_LEVEL: -O
      SWIFT_COMPILATION_MODE: wholemodule

targets:
  DICOMViewer:
    type: application
    platform: visionOS
    sources:
      - path: App
      - path: Models
      - path: ViewModels
      - path: Views
      - path: Services
    dependencies:
      - package: DICOMKit
        product: DICOMCore
      - package: DICOMKit
        product: DICOMDictionary
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dicomkit.viewer.visionos
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UIRequiredDeviceCapabilities: ["arm64"]
        INFOPLIST_KEY_NSHandTrackingUsageDescription: "DICOMViewer uses hand tracking for natural gesture-based interaction with medical images and 3D volumes."
        INFOPLIST_KEY_NSEyeTrackingUsageDescription: "DICOMViewer uses eye tracking for gaze-based UI interaction and hands-free navigation."
        INFOPLIST_KEY_NSLocalNetworkUsageDescription: "DICOMViewer uses local network for SharePlay collaborative viewing sessions."
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "DICOMViewer uses the microphone for voice annotations and collaborative voice chat."
        INFOPLIST_KEY_UISupportsDocumentBrowser: true

  DICOMViewerTests:
    type: bundle.unit-test
    platform: visionOS
    sources:
      - path: Tests
    dependencies:
      - target: DICOMViewer
      - package: DICOMKit
        product: DICOMCore
      - package: DICOMKit
        product: DICOMDictionary
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dicomkit.viewer.visionos.tests
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/DICOMViewer.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/DICOMViewer

schemes:
  DICOMViewer:
    build:
      targets:
        DICOMViewer: all
        DICOMViewerTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: DICOMViewerTests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
