name: DICOMViewer
options:
  bundleIdPrefix: com.rasterlab
  deploymentTarget:
    macOS: "14.0"
  
packages:
  DICOMKit:
    path: ..

targets:
  DICOMViewer:
    type: application
    platform: macOS
    sources:
      - App
      - Models
      - ViewModels
      - Views
      - Services
    dependencies:
      - package: DICOMKit
        product: DICOMKit
      - package: DICOMKit
        product: DICOMCore
      - package: DICOMKit
        product: DICOMNetwork
    settings:
      PRODUCT_NAME: DICOMViewer
      PRODUCT_BUNDLE_IDENTIFIER: com.rasterlab.dicomviewer.macos
      INFOPLIST_FILE: Info.plist
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      SWIFT_VERSION: "5.9"
      ENABLE_PREVIEWS: YES
      DEVELOPMENT_ASSET_PATHS: "\"DICOMViewer/Preview Content\""
    scheme:
      testTargets:
        - DICOMViewerTests

  DICOMViewerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests
    dependencies:
      - target: DICOMViewer
      - package: DICOMKit
        product: DICOMKit
    settings:
      PRODUCT_NAME: DICOMViewerTests
      PRODUCT_BUNDLE_IDENTIFIER: com.rasterlab.dicomviewer.macos.tests
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      SWIFT_VERSION: "5.9"
