name: Feature Request
description: Suggest a new feature or enhancement for DICOMKit
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand and evaluate your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches could solve this problem?

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        In my medical imaging app, I need to...
    validations:
      required: true

  - type: textarea
    id: api-example
    attributes:
      label: Proposed API (Optional)
      description: If you have an idea of how the API should look, share it here
      render: swift
      placeholder: |
        // Example usage
        let result = try dataset.someNewMethod()

  - type: dropdown
    id: dicom-standard
    attributes:
      label: DICOM Standard Compliance
      description: Is this feature specified in the DICOM standard?
      options:
        - "Yes - Part of DICOM 2026a standard"
        - "No - Enhancement/convenience feature"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: dicom-reference
    attributes:
      label: DICOM Standard Reference
      description: If this is part of the DICOM standard, provide the reference (e.g., PS3.3 Section 7.4)
      placeholder: "PS3.x Section Y.Z"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Critical - Blocking my project"
        - "High - Would significantly improve my workflow"
        - "Medium - Nice to have"
        - "Low - Just an idea"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Target Platform(s)
      description: Which platform(s) should this feature support?
      multiple: true
      options:
        - All platforms (iOS, macOS, visionOS)
        - iOS
        - macOS
        - visionOS
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, diagrams, or screenshots about the feature request
      placeholder: Any other information that would help us understand your request

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing this feature?
      options:
        - label: I would be willing to implement this feature and submit a PR
          required: false
