// AnonRoundTripTests.swift
// Oracle-based round-trip tests for the `dicom-anon` tool.
// Tests exercise the DICOMKit `Anonymizer` (PS3.15 Annex E engine) directly —
// never the CLI binary.

import XCTest
import Foundation
@testable import DICOMKit
@testable import DICOMCore

final class AnonRoundTripTests: XCTestCase {

    private typealias Options = ConfidentialityProfile.Options

    // MARK: - Private helpers

    /// Builds a small MONOCHROME2 fixture seeded with identifiable PHI so the
    /// engine has real values to zero / remove / regenerate.
    private func makePHIFixture(
        patientName: String = "John^Smith",
        patientID: String = "MRN-123",
        birthDate: String = "19800101",
        studyDate: String = "20200101",
        sopInstanceUID: String = "1.2.3.4.5.6.7.8.9"
    ) -> DICOMFile {
        var ds = DataSet()
        ds.setString("1.2.840.10008.5.1.4.1.1.2", for: .sopClassUID, vr: .UI)
        ds.setString(sopInstanceUID, for: .sopInstanceUID, vr: .UI)
        ds.setString("1.2.3.4.5.100", for: .studyInstanceUID, vr: .UI)
        ds.setString("1.2.3.4.5.200", for: .seriesInstanceUID, vr: .UI)
        ds.setString("CT", for: .modality, vr: .CS)
        ds.setString(patientName, for: .patientName, vr: .PN)
        ds.setString(patientID, for: .patientID, vr: .LO)
        ds.setString(birthDate, for: .patientBirthDate, vr: .DA)
        ds.setString(studyDate, for: .studyDate, vr: .DA)
        ds.setString("120000", for: .studyTime, vr: .TM)
        ds.setString("General Hospital", for: .institutionName, vr: .LO)
        ds.setString("PRIVATE PHI", for: Tag(group: 0x0009, element: 0x0010), vr: .LO)
        ds.setUInt16(4, for: .rows)
        ds.setUInt16(4, for: .columns)
        ds.setUInt16(8, for: .bitsAllocated)
        ds.setUInt16(8, for: .bitsStored)
        ds.setUInt16(7, for: .highBit)
        ds.setUInt16(0, for: .pixelRepresentation)
        ds.setUInt16(1, for: .samplesPerPixel)
        ds.setString("MONOCHROME2", for: .photometricInterpretation, vr: .CS)
        let count = 16
        let pixels = Data((0..<count).map { UInt8($0 % 256) })
        ds[.pixelData] = DataElement.data(tag: .pixelData, vr: .OB, data: pixels)
        return DICOMFile.create(dataSet: ds, sopClassUID: "1.2.840.10008.5.1.4.1.1.2")
    }

    private let identityRemoved = Tag(group: 0x0012, element: 0x0062)

    // MARK: - Tests

    // Oracle: the Basic Profile zeroes the Type 2 identifiers (present, empty) and
    // removes the Type 3 ones — never leaves a source value behind.
    func testBasicProfileRemovesOrZeroesPHI() throws {
        let src = makePHIFixture()
        let (out, _) = Anonymizer().deidentify(file: src, filePath: "in.dcm")

        XCTAssertEqual(out.dataSet.string(for: .patientName), "", "PatientName is Z: present but empty")
        XCTAssertEqual(out.dataSet.string(for: .patientID), "", "PatientID is Z")
        XCTAssertEqual(out.dataSet.string(for: .patientBirthDate), "", "Birth Date is Z")
        XCTAssertNil(out.dataSet[.institutionName], "Institution Name is X")
        XCTAssertNil(out.dataSet[Tag(group: 0x0009, element: 0x0010)], "private tags are removed")
        XCTAssertEqual(out.dataSet.string(for: .studyDate), "", "dates are zeroed without a retention option")
        XCTAssertEqual(out.dataSet.string(for: identityRemoved), "YES")
    }

    // Oracle: every changed tag is reported exactly once in result.changedTags.
    func testChangedTagsReportedOncePerTag() throws {
        let src = makePHIFixture()
        let (_, result) = Anonymizer().deidentify(file: src, filePath: "in.dcm")

        XCTAssertTrue(result.success)
        XCTAssertEqual(Set(result.changedTags).count, result.changedTags.count,
                       "no tag should appear more than once in changedTags")
        XCTAssertTrue(result.changedTags.contains(.patientName))
    }

    // Oracle: non-PHI tags (Modality, Rows, BitsAllocated) are untouched.
    func testNonPHITagsPreserved() throws {
        let src = makePHIFixture()
        let (out, _) = Anonymizer().deidentify(file: src, filePath: "in.dcm")

        XCTAssertEqual(out.dataSet.string(for: .modality), src.dataSet.string(for: .modality))
        XCTAssertEqual(out.dataSet.uint16(for: .rows), src.dataSet.uint16(for: .rows))
        XCTAssertEqual(out.dataSet.uint16(for: .columns), src.dataSet.uint16(for: .columns))
        XCTAssertEqual(out.dataSet.uint16(for: .bitsAllocated), src.dataSet.uint16(for: .bitsAllocated))
    }

    // Oracle: pixel bytes are byte-for-byte identical after the header pass.
    func testPixelDataUnchanged() throws {
        let src = makePHIFixture()
        let (out, _) = Anonymizer().deidentify(file: src, filePath: "in.dcm")
        XCTAssertEqual(pixelBytes(out), pixelBytes(src))
    }

    // Oracle: UIDs are regenerated by default and kept under Retain UIDs.
    func testUIDRegenerationVsRetain() throws {
        let src = makePHIFixture()

        let (retainOut, _) = Anonymizer(options: Options(retainUIDs: true)).deidentify(file: src, filePath: "in.dcm")
        XCTAssertEqual(retainOut.dataSet.string(for: .sopInstanceUID), src.dataSet.string(for: .sopInstanceUID))
        XCTAssertEqual(retainOut.dataSet.string(for: .studyInstanceUID), src.dataSet.string(for: .studyInstanceUID))

        let (regenOut, _) = Anonymizer().deidentify(file: src, filePath: "in.dcm")
        XCTAssertNotEqual(regenOut.dataSet.string(for: .sopInstanceUID), src.dataSet.string(for: .sopInstanceUID))
        XCTAssertNotEqual(regenOut.dataSet.string(for: .studyInstanceUID), src.dataSet.string(for: .studyInstanceUID))
        XCTAssertNotEqual(regenOut.dataSet.string(for: .seriesInstanceUID), src.dataSet.string(for: .seriesInstanceUID))
        XCTAssertEqual(regenOut.dataSet.string(for: .sopClassUID), "1.2.840.10008.5.1.4.1.1.2", "class UIDs survive")
    }

    // Oracle: UID mapping is a deterministic 1:1 map — identical original UIDs
    // regenerate to identical new UIDs within one instance AND across the files
    // of one run (that is what keeps a study together).
    func testUIDMappingIsConsistentWithinRun() throws {
        var ds = DataSet()
        ds.setString("1.2.840.10008.5.1.4.1.1.2", for: .sopClassUID, vr: .UI)
        ds.setString("1.2.3.4.5.999", for: .sopInstanceUID, vr: .UI)
        ds.setString("1.2.3.4.5.777", for: .studyInstanceUID, vr: .UI)
        ds.setString("1.2.3.4.5.777", for: .seriesInstanceUID, vr: .UI)
        let src = DICOMFile.create(dataSet: ds, sopClassUID: "1.2.840.10008.5.1.4.1.1.2")

        let anonymizer = Anonymizer()
        let (out, _) = anonymizer.deidentify(file: src, filePath: "a.dcm")
        let newStudy = out.dataSet.string(for: .studyInstanceUID)
        XCTAssertNotNil(newStudy)
        XCTAssertEqual(newStudy, out.dataSet.string(for: .seriesInstanceUID))
        XCTAssertNotEqual(newStudy, "1.2.3.4.5.777")

        let (sibling, _) = anonymizer.deidentify(file: makePHIFixture(sopInstanceUID: "1.2.3.4.5.998"), filePath: "b.dcm")
        let (again, _) = anonymizer.deidentify(file: src, filePath: "c.dcm")
        XCTAssertEqual(again.dataSet.string(for: .studyInstanceUID), newStudy, "same run, same map")
        XCTAssertNotEqual(sibling.dataSet.string(for: .sopInstanceUID), again.dataSet.string(for: .sopInstanceUID))
    }

    // Oracle: Modified Dates preserves YYYYMMDD format; 20200101 + 30 == 20200131,
    // and the time of day is untouched by a whole-day shift.
    func testShiftDatesPreservesFormatAndOffset() throws {
        let src = makePHIFixture(studyDate: "20200101")
        let (out, _) = Anonymizer(options: Options(retainLongitudinalTemporal: true, dateOffsetDays: 30))
            .deidentify(file: src, filePath: "in.dcm")
        XCTAssertEqual(out.dataSet.string(for: .studyDate), "20200131")
        XCTAssertEqual(out.dataSet.string(for: .studyTime), "120000")
        XCTAssertEqual(out.dataSet.string(for: .patientBirthDate), "19800131",
                       "Modified Dates shifts the birth date too — the real DOB must not survive")
    }

    // Oracle: Full Dates keeps dates verbatim.
    func testRetainDatesKeepsOriginal() throws {
        let src = makePHIFixture(studyDate: "20200101")
        let (out, _) = Anonymizer(options: Options(retainLongitudinalTemporal: true))
            .deidentify(file: src, filePath: "in.dcm")
        XCTAssertEqual(out.dataSet.string(for: .studyDate), "20200101")
    }

    // Oracle: the file states which profile and options were applied.
    func testMethodCodesRecorded() throws {
        let src = makePHIFixture()
        let (out, _) = Anonymizer(options: Options(retainInstitutionIdentity: true, dateOffsetDays: 5))
            .deidentify(file: src, filePath: "in.dcm")
        let codes = ConfidentialityProfile.MethodCode.recorded(in: out.dataSet)
        XCTAssertTrue(codes.contains("113100"))
        XCTAssertTrue(codes.contains("113112"))
        XCTAssertFalse(codes.contains("113107"), "an offset without the retain option is not Modified Dates")
        let method = out.dataSet.string(for: Tag(group: 0x0012, element: 0x0063)) ?? ""
        XCTAssertTrue(method.contains("Basic Application Level Confidentiality Profile"), method)
        XCTAssertTrue(method.contains("Retain Institution Identity"), method)
    }

    // Oracle: audit log records one entry per change, carries no values, and writes
    // deterministically to disk.
    func testAuditLogRecordsChangesWithoutValues() throws {
        let src = makePHIFixture()
        let anonymizer = Anonymizer()
        let (_, result) = anonymizer.deidentify(file: src, filePath: "in.dcm")

        let log = anonymizer.getAuditLog()
        XCTAssertEqual(log.count, result.changedTags.count)
        XCTAssertTrue(log.allSatisfy { $0.filePath == "in.dcm" })
        XCTAssertTrue(log.allSatisfy { $0.note == nil })

        let dir = try makeTempDir()
        let logURL = dir.appendingPathComponent("audit.log")
        try anonymizer.writeAuditLog(to: logURL)
        let text = try String(contentsOf: logURL, encoding: .utf8)
        XCTAssertTrue(text.contains("De-identification Audit Log"))
        XCTAssertFalse(text.contains("John"), "never the original value")
        XCTAssertFalse(text.contains("MRN-123"))
    }

    // Oracle: de-identified file round-trips through write()/read() and the zeroed
    // values persist across serialization.
    func testAnonymizedFileRoundTripsThroughDisk() throws {
        let src = makePHIFixture()
        let (out, _) = Anonymizer().deidentify(file: src, filePath: "in.dcm")

        let data = try out.write()
        let reread = try DICOMFile.read(from: data, force: false)
        XCTAssertEqual(reread.dataSet.string(for: .patientName), "")
        XCTAssertEqual(reread.dataSet.string(for: .patientBirthDate), "")
        XCTAssertEqual(reread.dataSet.string(for: identityRemoved), "YES")
        XCTAssertEqual(pixelBytes(reread), pixelBytes(src))
    }

    // Oracle (corpus / realism): de-identifying a real Implicit-VR-LE MR file zeroes
    // PatientName and preserves Modality + pixel bytes.
    func testCorpusMRAnonymizationPreservesPixelsAndModality() throws {
        let f = try loadCorpus(.mr)
        try XCTSkipIf(f == nil, "corpus absent")
        let src = try XCTUnwrap(f)

        let originalModality = src.dataSet.string(for: .modality)
        let originalPixels = pixelBytes(src)

        let (out, _) = Anonymizer().deidentify(file: src, filePath: "MR.dcm")

        XCTAssertEqual(out.dataSet.string(for: .modality), originalModality)
        XCTAssertEqual(pixelBytes(out), originalPixels)
        if src.dataSet[.patientName] != nil {
            XCTAssertEqual(out.dataSet.string(for: .patientName), "")
        }
    }
}
