#!/usr/bin/env python3
"""
cli_parity_report.py  —  Tier 1 of the DICOMKit CLI parity harness.

Compares, for every DICOMKit CLI command:
  * the REAL input contract  — parsed from `<binary> --experimental-dump-help`
    JSON (swift-argument-parser ToolInfoV0), and
  * the STUDIO-declared input contract — parsed from the JSON emitted by the
    `studio-cli-introspect` executable (DICOMStudio's `ToolCatalogHelpers`).

It writes a colour-coded multi-sheet .xlsx:
  - Summary        one row per Studio tool + every CLI-only binary
  - Input Parity   one row per (tool, flag) with MATCH / mismatch status
  - Tool Coverage  one row per CLI binary (has Studio entry? executeCommand?)
  - About          legend + caveats

This is INPUT-CONTRACT parity only (Tier 1). Output parity (running the binary
vs. driving CLIWorkshopViewModel.executeCommand()) is a separate later tier.

Usage:
  python3 cli_parity_report.py --cli-dir DIR --studio FILE --out FILE.xlsx
"""

import argparse
import json
import os
import sys

try:
    from openpyxl import Workbook
    from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
except ImportError:
    sys.stderr.write(
        "ERROR: openpyxl is not installed.\n"
        "Install it (ideally in a venv):  python3 -m pip install openpyxl\n"
        "Or just run Scripts/cli-parity.sh which sets up a venv automatically.\n"
    )
    sys.exit(2)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Flags injected by swift-argument-parser itself — not a Studio concern.
FRAMEWORK_FLAGS = {"--help", "-h", "--version", "--experimental-dump-help"}

# Tools whose output `CLIWorkshopViewModel.executeCommand()` actually produces
# (the `switch tool.id` cases). Everything else hits the "not yet supported"
# default branch. Source: Sources/DICOMStudio/ViewModels/CLIWorkshopViewModel.swift
EXECUTE_SUPPORTED = {
    "dicom-echo", "dicom-query", "dicom-send", "dicom-retrieve", "dicom-qr",
    "dicom-mwl", "dicom-mpps", "dicom-qido", "dicom-wado", "dicom-stow",
    "dicom-ups", "dicom-convert", "dicom-validate", "dicom-anon", "dicom-info",
    "dicom-dump", "dicom-tags", "dicom-diff",
}

# Fills
FILL_MATCH    = PatternFill("solid", fgColor="C6EFCE")  # green
FILL_BAD      = PatternFill("solid", fgColor="FFC7CE")  # red
FILL_WARN     = PatternFill("solid", fgColor="FFEB9C")  # amber
FILL_HEADER   = PatternFill("solid", fgColor="305496")  # dark blue
FILL_INFO     = PatternFill("solid", fgColor="DDEBF7")  # light blue
FONT_HEADER   = Font(color="FFFFFF", bold=True)
FONT_BOLD     = Font(bold=True)
THIN = Side(style="thin", color="D9D9D9")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
WRAP = Alignment(vertical="top", wrap_text=True)
TOP = Alignment(vertical="top")


# ---------------------------------------------------------------------------
# CLI dump-help parsing (swift-argument-parser ToolInfoV0)
# ---------------------------------------------------------------------------

def arg_long_flags(arg):
    """Return the list of '--name' long flags for an argument node."""
    out = []
    for n in arg.get("names", []) or []:
        if n.get("kind") == "long":
            out.append("--" + n["name"])
        elif n.get("kind") == "longWithSingleDash":
            out.append("-" + n["name"])
    return out


def arg_short_flags(arg):
    out = []
    for n in arg.get("names", []) or []:
        if n.get("kind") == "short":
            out.append("-" + n["name"])
    return out


def normalize_arg(arg):
    """Flatten one ToolInfo argument node into a simple dict."""
    return {
        "kind": arg.get("kind"),                      # positional|option|flag
        "long": arg_long_flags(arg),
        "short": arg_short_flags(arg),
        "valueName": arg.get("valueName"),
        "isOptional": arg.get("isOptional", True),
        "isRepeating": arg.get("isRepeating", False),
        "default": arg.get("defaultValue"),
        "abstract": arg.get("abstract", ""),
        "shouldDisplay": arg.get("shouldDisplay", True),
    }


def walk_command(cmd, path):
    """
    Yield (subpath, node_args) for the root command and every subcommand.
    subpath is the space-joined subcommand path ('' for root, 'query', etc.).
    """
    args = [normalize_arg(a) for a in (cmd.get("arguments") or [])]
    yield (path, args)
    for sub in (cmd.get("subcommands") or []):
        name = sub.get("commandName", "")
        if name == "help":      # auto-generated by swift-argument-parser
            continue
        child_path = (path + " " + name).strip() if path else name
        for item in walk_command(sub, child_path):
            yield item


def load_cli_tool(filepath):
    """Load one CLI dump-help JSON -> {'binary':..., 'nodes':{subpath:[args]}}."""
    with open(filepath) as f:
        data = json.load(f)
    cmd = data.get("command", {})
    binary = cmd.get("commandName") or os.path.splitext(os.path.basename(filepath))[0]
    nodes = {}
    for subpath, args in walk_command(cmd, ""):
        nodes[subpath] = args
    return {"binary": binary, "nodes": nodes}


def option_groups(args):
    """
    Group a node's option/flag args into option records, excluding framework +
    hidden flags. Each option = the full set of its long+short tokens, so a
    Studio long-form match also covers the short alias.
    Returns (options, positionals).
      option = {tokens:set, primary:str, kind, default, abstract}
    """
    options = []
    positionals = []
    for a in args:
        if not a.get("shouldDisplay", True):
            continue
        if a["kind"] == "positional":
            positionals.append(a)
            continue
        toks = [t for t in (a["long"] + a["short"]) if t not in FRAMEWORK_FLAGS]
        if not toks:
            continue
        primary = a["long"][0] if a["long"] else toks[0]
        options.append({
            "tokens": set(toks), "primary": primary, "kind": a["kind"],
            "default": a.get("default"), "abstract": a.get("abstract", ""),
        })
    return options, positionals


def accepted_for_target(cli_tool, subpath, union_all):
    """
    Compute accepted (option_records, positionals) for a Studio tool's target.
    If union_all, merge root + ALL subcommands (lenient — used when a Studio
    tool maps to a binary root that itself has subcommands). Otherwise merge
    root args + the specific subpath node. Options are de-duplicated by primary.
    """
    nodes = cli_tool["nodes"]
    if union_all:
        sources = list(nodes.values())
    else:
        sources = []
        if "" in nodes:
            sources.append(nodes[""])          # root-level globals
        if subpath and subpath in nodes:
            sources.append(nodes[subpath])
        elif not subpath:
            sources = [nodes.get("", [])]
    by_primary = {}
    positionals = []
    for args in sources:
        opts, pos = option_groups(args)
        for o in opts:
            by_primary.setdefault(o["primary"], o)
        positionals.extend(pos)
    return list(by_primary.values()), positionals


# ---------------------------------------------------------------------------
# Studio catalog parsing
# ---------------------------------------------------------------------------

def split_name(name):
    """'dicom-wado query' -> ('dicom-wado', 'query');  'dicom-info' -> ('dicom-info','')."""
    parts = name.split(" ", 1)
    return (parts[0], parts[1].strip() if len(parts) > 1 else "")


def studio_flag_set(tool):
    """
    The flag/option TOKENS the Studio actually emits, straight from the
    introspector's `emittedFlags` (which ran buildCommand()). This is the true
    invocation contract — positional-endpoint folding (host:port), flagPicker
    (`--value`) and internal cliMapping tokens are all already applied.
    """
    return set(tool.get("emittedFlags", []))


def studio_meta_lookup(tool):
    """Best-effort flag token -> param dict, for default/help columns."""
    lut = {}
    for p in tool.get("parameters", []):
        flag = p.get("flag", "")
        if flag.startswith("-"):
            lut.setdefault(flag, p)
        if p.get("type") == "FLAG_PICKER":
            for v in p.get("allowedValues", []):
                lut.setdefault("--" + v, p)
    return lut


def studio_positionals(tool):
    return [p for p in tool.get("parameters", [])
            if p.get("isPositional") and not p.get("isInternal")]


# ---------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------

def compare_tool(tool, cli_tool):
    """
    Returns (summary_dict, detail_rows[]).
    detail_rows: list of dicts with per-flag MATCH/mismatch status.
    """
    binary, subpath = split_name(tool["name"])
    union_all = (cli_tool is not None) and (subpath == "") and \
                any(k for k in cli_tool["nodes"] if k != "")
    mode = "union" if union_all else ("subcommand:" + subpath if subpath else "exact")

    s_flags = studio_flag_set(tool)
    s_lut = studio_meta_lookup(tool)
    s_pos = studio_positionals(tool)
    if cli_tool is None:
        accepted, c_pos = [], []
    else:
        accepted, c_pos = accepted_for_target(cli_tool, subpath, union_all)

    all_accepted_tokens = set()
    for o in accepted:
        all_accepted_tokens |= o["tokens"]

    rows = []
    n_match = n_extra = n_missing = 0
    matched_studio = set()

    def mkrow(flag, kind, in_cli, in_studio, cli_def, studio_def, cli_help, studio_help, status):
        return {
            "tool": tool["id"], "binary": binary, "subcmd": subpath, "mode": mode,
            "flag": flag, "kind": kind,
            "in_cli": in_cli, "in_studio": in_studio,
            "cli_default": cli_def or "", "studio_default": studio_def or "",
            "cli_help": cli_help or "", "studio_help": studio_help or "",
            "status": status,
        }

    # One row per real CLI option: is it reachable from the Studio? (a long-form
    # match also covers the option's short alias, since options compare by token set)
    for o in sorted(accepted, key=lambda x: x["primary"]):
        hit = o["tokens"] & s_flags
        if hit:
            n_match += 1; matched_studio |= hit
            p = s_lut.get(sorted(hit)[0], {})
            rows.append(mkrow(o["primary"], o["kind"], "yes", "yes",
                              o["default"], p.get("defaultValue"),
                              o["abstract"], p.get("helpText"), "MATCH"))
        else:
            n_missing += 1
            rows.append(mkrow(o["primary"], o["kind"], "yes", "no",
                              o["default"], "", o["abstract"], "", "MISSING_IN_STUDIO"))

    # Studio-emitted flags the CLI does NOT accept -> real drift (would error).
    for flag in sorted(s_flags):
        if flag in all_accepted_tokens:
            continue
        p = s_lut.get(flag, {})
        if cli_tool is None:
            status = "NO_CLI_BINARY"
        else:
            status = "EXTRA_IN_STUDIO"; n_extra += 1
        rows.append(mkrow(flag, p.get("type", ""), "no", "yes",
                          "", p.get("defaultValue"), "", p.get("helpText"), status))

    total = n_match + n_extra + n_missing
    parity = (100.0 * n_match / total) if total else (100.0 if not s_flags else 0.0)

    if cli_tool is None:
        overall = "NO_CLI_BINARY"
    elif not tool.get("parameters"):
        overall = "NO_PARAMS_DEFINED"
    elif n_extra == 0 and n_missing == 0:
        overall = "OK"
    elif n_extra > 0:
        overall = "DRIFT"      # Studio declares flags the CLI rejects -> would error
    else:
        overall = "INCOMPLETE" # Studio just doesn't expose some CLI flags

    summary = {
        "tool": tool["id"], "binary": binary, "subcmd": subpath, "mode": mode,
        "net": "yes" if tool.get("requiresNetwork") else "no",
        "exec": "yes" if tool["id"] in EXECUTE_SUPPORTED else "no",
        "studio_flags": len(s_flags), "cli_flags": len(accepted),
        "match": n_match, "extra_in_studio": n_extra, "missing_in_studio": n_missing,
        "studio_pos": len(s_pos), "cli_pos": len(c_pos),
        "parity_pct": round(parity, 1), "status": overall,
    }
    return summary, rows


# ---------------------------------------------------------------------------
# Excel writing
# ---------------------------------------------------------------------------

STATUS_FILL = {
    "MATCH": FILL_MATCH, "OK": FILL_MATCH,
    "EXTRA_IN_STUDIO": FILL_BAD, "DRIFT": FILL_BAD, "NO_CLI_BINARY": FILL_BAD,
    "MISSING_IN_STUDIO": FILL_WARN, "INCOMPLETE": FILL_WARN,
    "NO_PARAMS_DEFINED": FILL_WARN, "MISSING_TOOL": FILL_BAD,
}


def write_header(ws, headers):
    for col, h in enumerate(headers, start=1):
        c = ws.cell(row=1, column=col, value=h)
        c.fill = FILL_HEADER
        c.font = FONT_HEADER
        c.alignment = Alignment(vertical="center", wrap_text=True)
        c.border = BORDER
    ws.freeze_panes = "A2"


def autosize(ws, widths):
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w


def build_summary_sheet(wb, summaries, cli_only):
    ws = wb.create_sheet("Summary")
    headers = ["Tool (Studio id)", "Binary", "Subcmd", "Match mode", "Network",
               "execCmd?", "Studio flags", "CLI flags", "Matched",
               "Extra in Studio", "Missing in Studio", "Parity %", "Status"]
    write_header(ws, headers)
    r = 2
    for s in summaries:
        vals = [s["tool"], s["binary"], s["subcmd"], s["mode"], s["net"], s["exec"],
                s["studio_flags"], s["cli_flags"], s["match"], s["extra_in_studio"],
                s["missing_in_studio"], s["parity_pct"], s["status"]]
        for col, v in enumerate(vals, start=1):
            cell = ws.cell(row=r, column=col, value=v)
            cell.border = BORDER
            cell.alignment = TOP
        ws.cell(row=r, column=13).fill = STATUS_FILL.get(s["status"], FILL_WARN)
        if s["extra_in_studio"]:
            ws.cell(row=r, column=10).fill = FILL_BAD
        if s["missing_in_studio"]:
            ws.cell(row=r, column=11).fill = FILL_WARN
        r += 1
    # CLI binaries with no Studio tool at all
    for binary in cli_only:
        vals = [f"(none)", binary, "", "n/a", "", "no", 0, "?", 0, 0, "?", 0.0,
                "MISSING_TOOL"]
        for col, v in enumerate(vals, start=1):
            cell = ws.cell(row=r, column=col, value=v)
            cell.border = BORDER
            cell.alignment = TOP
        ws.cell(row=r, column=13).fill = FILL_BAD
        ws.cell(row=r, column=2).fill = FILL_BAD
        r += 1
    autosize(ws, [22, 16, 12, 16, 9, 9, 11, 10, 9, 14, 16, 10, 18])


def build_detail_sheet(wb, rows):
    ws = wb.create_sheet("Input Parity")
    headers = ["Tool", "Binary", "Subcmd", "Flag", "Kind", "In CLI", "In Studio",
               "CLI default", "Studio default", "CLI help", "Studio help", "Status"]
    write_header(ws, headers)
    r = 2
    for row in rows:
        vals = [row["tool"], row["binary"], row["subcmd"], row["flag"], row["kind"],
                row["in_cli"], row["in_studio"], row["cli_default"],
                row["studio_default"], row["cli_help"], row["studio_help"], row["status"]]
        for col, v in enumerate(vals, start=1):
            cell = ws.cell(row=r, column=col, value=v)
            cell.border = BORDER
            cell.alignment = WRAP if col in (10, 11) else TOP
        ws.cell(row=r, column=12).fill = STATUS_FILL.get(row["status"], FILL_WARN)
        r += 1
    ws.auto_filter.ref = "A1:L%d" % (r - 1)
    autosize(ws, [16, 14, 10, 22, 11, 7, 9, 18, 16, 34, 34, 18])


def build_coverage_sheet(wb, cli_tools, studio_by_binary):
    ws = wb.create_sheet("Tool Coverage")
    headers = ["CLI binary", "Has Studio entry?", "Studio tool id(s)",
               "executeCommand() support?", "Subcommands", "Notes"]
    write_header(ws, headers)
    r = 2
    for binary in sorted(cli_tools.keys()):
        ids = studio_by_binary.get(binary, [])
        has = "yes" if ids else "NO"
        subs = [k for k in cli_tools[binary]["nodes"] if k]
        exec_ids = [i for i in ids if i in EXECUTE_SUPPORTED]
        exec_txt = ("yes: " + ",".join(exec_ids)) if exec_ids else ("no" if ids else "n/a")
        note = ""
        if not ids:
            note = "No CLI Workshop catalog entry — tool unreachable from the UI."
        elif not exec_ids:
            note = "Catalog entry exists but executeCommand() has no case (output not produced)."
        vals = [binary, has, ", ".join(ids), exec_txt,
                ", ".join(subs) if subs else "", note]
        for col, v in enumerate(vals, start=1):
            cell = ws.cell(row=r, column=col, value=v)
            cell.border = BORDER
            cell.alignment = WRAP if col == 6 else TOP
        ws.cell(row=r, column=2).fill = FILL_MATCH if ids else FILL_BAD
        if ids:
            ws.cell(row=r, column=4).fill = FILL_MATCH if exec_ids else FILL_WARN
        r += 1
    autosize(ws, [18, 18, 26, 30, 22, 52])


def build_about_sheet(wb, meta):
    ws = wb.create_sheet("About")
    lines = [
        ("DICOMKit CLI Parity Report — Tier 1 (input-contract parity)", FONT_BOLD),
        ("", None),
        ("Generated by Scripts/cli-parity.sh", None),
        ("  CLI side   : <binary> --experimental-dump-help  (swift-argument-parser ToolInfoV0)", None),
        ("  Studio side: studio-cli-introspect  (DICOMStudio ToolCatalogHelpers)", None),
        ("", None),
        ("CLI binaries dumped : %d" % meta["cli_count"], None),
        ("Studio catalog tools: %d" % meta["studio_count"], None),
        ("", None),
        ("Status legend", FONT_BOLD),
        ("  OK                 Studio flags exactly match the CLI's accepted flags.", None),
        ("  DRIFT  (red)       Studio declares a flag the real CLI REJECTS — the generated", None),
        ("                     command would fail. Highest priority to fix.", None),
        ("  INCOMPLETE (amber) Studio is missing flags the CLI accepts (UI can't drive them).", None),
        ("  NO_PARAMS_DEFINED  Studio has a catalog entry but zero parameters wired up.", None),
        ("  MISSING_TOOL (red) CLI binary has no Studio CLI-Workshop entry at all.", None),
        ("  NO_CLI_BINARY      Studio tool maps to a binary that wasn't dumped (not built / N/A).", None),
        ("", None),
        ("Per-flag statuses (Input Parity sheet)", FONT_BOLD),
        ("  MATCH              flag present on both sides.", None),
        ("  EXTRA_IN_STUDIO    Studio declares it; CLI does not accept it (would error).", None),
        ("  MISSING_IN_STUDIO  CLI accepts it; Studio doesn't expose it.", None),
        ("", None),
        ("Match modes", FONT_BOLD),
        ("  exact              flat command — Studio flags compared 1:1 with CLI args.", None),
        ("  subcommand:<name>  Studio tool maps to a CLI subcommand (e.g. dicom-wado query).", None),
        ("  union              Studio maps to a binary root that itself has subcommands;", None),
        ("                     accepted set = union of root + all subcommands (lenient —", None),
        ("                     won't catch 'right flag, wrong subcommand').", None),
        ("", None),
        ("Caveats", FONT_BOLD),
        ("  * Tier 1 checks INPUT CONTRACTS only. Output parity (binary stdout vs.", None),
        ("    CLIWorkshopViewModel.executeCommand() console output) is a separate tier.", None),
        ("  * CLI 'default' values are display strings from ArgumentParser and may not be", None),
        ("    literal — shown side-by-side for reference, not used to flag mismatches.", None),
        ("  * Positional arguments are counted (Studio_pos / cli_pos) but not name-matched.", None),
    ]
    for i, (text, font) in enumerate(lines, start=1):
        c = ws.cell(row=i, column=1, value=text)
        if font:
            c.font = font
    ws.column_dimensions["A"].width = 96


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description="Generate DICOMKit CLI parity .xlsx report")
    ap.add_argument("--cli-dir", required=True, help="dir of <binary>.json dump-help files")
    ap.add_argument("--studio", required=True, help="studio-catalog.json from studio-cli-introspect")
    ap.add_argument("--out", required=True, help="output .xlsx path")
    args = ap.parse_args()

    # Load CLI dumps
    cli_tools = {}
    for fn in sorted(os.listdir(args.cli_dir)):
        if not fn.endswith(".json"):
            continue
        try:
            t = load_cli_tool(os.path.join(args.cli_dir, fn))
            cli_tools[t["binary"]] = t
        except Exception as e:
            sys.stderr.write("WARN: failed to parse %s: %s\n" % (fn, e))

    # Load Studio catalog
    with open(args.studio) as f:
        studio = json.load(f)
    studio_tools = studio.get("tools", [])

    # Map binary -> [studio tool ids]
    studio_by_binary = {}
    for t in studio_tools:
        binary, _ = split_name(t["name"])
        studio_by_binary.setdefault(binary, []).append(t["id"])

    # Compare
    summaries = []
    detail_rows = []
    for t in studio_tools:
        binary, _ = split_name(t["name"])
        cli_tool = cli_tools.get(binary)
        s, rows = compare_tool(t, cli_tool)
        summaries.append(s)
        detail_rows.extend(rows)

    # Sort: worst first (DRIFT, then MISSING/INCOMPLETE, then OK)
    order = {"DRIFT": 0, "NO_CLI_BINARY": 1, "NO_PARAMS_DEFINED": 2,
             "INCOMPLETE": 3, "OK": 4}
    summaries.sort(key=lambda s: (order.get(s["status"], 9), s["tool"]))

    cli_only = sorted(b for b in cli_tools if b not in studio_by_binary)

    # Build workbook
    wb = Workbook()
    wb.remove(wb.active)  # drop default sheet
    build_summary_sheet(wb, summaries, cli_only)
    build_detail_sheet(wb, detail_rows)
    build_coverage_sheet(wb, cli_tools, studio_by_binary)
    build_about_sheet(wb, {"cli_count": len(cli_tools), "studio_count": len(studio_tools)})

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    wb.save(args.out)

    # Console summary
    n_drift = sum(1 for s in summaries if s["status"] == "DRIFT")
    n_incomplete = sum(1 for s in summaries if s["status"] == "INCOMPLETE")
    n_noparams = sum(1 for s in summaries if s["status"] == "NO_PARAMS_DEFINED")
    n_ok = sum(1 for s in summaries if s["status"] == "OK")
    print("CLI parity report written: %s" % args.out)
    print("  CLI binaries dumped     : %d" % len(cli_tools))
    print("  Studio catalog tools    : %d" % len(studio_tools))
    print("  OK                      : %d" % n_ok)
    print("  DRIFT (CLI rejects flag): %d" % n_drift)
    print("  INCOMPLETE (UI missing) : %d" % n_incomplete)
    print("  NO_PARAMS_DEFINED       : %d" % n_noparams)
    print("  CLI binaries w/o Studio : %d" % len(cli_only))
    if cli_only:
        print("    -> " + ", ".join(cli_only))


if __name__ == "__main__":
    main()
