"""Per-tool parameter-contract rows for Scripts/diff_cli.py: option -> (DICOM concept, 2026a reference,
allowed values / note, verdict). One block per tool, added as each tool is verified; the same rows appear
as the Input contract tables in DICOMCLI_STANDARD_IMPLEMENTATION.md."""
CONTRACT = {}

CONTRACT['dicom-echo'] = {
    '<host>': ('TCP transport address', 'PS3.8 9.1.1', 'host[:port]', 'plumbing'),
    '--port': ('TCP port', 'PS3.8 9.1.1 (well-known 104, registered 11112)', '1-65535; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 Table 6.2-1 VR AE', '<=16 bytes, no backslash/control, not all spaces (DICOMNetwork.AETitle)', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 Table 6.2-1 VR AE', 'as --aet; default "ANY-SCP" is a tool convention', 'plumbing'),
    '--count': ('number of C-ECHO operations', 'PS3.7 9.1.5', '> 0', 'plumbing'),
    '--timeout': ('ARTIM / socket timeout', 'PS3.8 9.1.2', 'seconds', 'plumbing'),
    '--stats': ('round-trip statistics', '', '', 'plumbing'),
    '--diagnose': ('connectivity probe; prints PS3.7 Tables D.3-1 / D.3-3 identification', 'PS3.7 Annex D.3', '', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
}

CONTRACT['dicom-send'] = {
    '<host>': ('TCP transport address', 'PS3.8 9.1.1', 'host[:port]', 'plumbing'),
    '--port': ('TCP port', 'PS3.8 9.1.1 (well-known 104, registered 11112)', '1-65535; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 Table 6.2-1 VR AE', '<=16 bytes (DICOMNetwork.AETitle)', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 Table 6.2-1 VR AE', 'as --aet; default "ANY-SCP" is a tool convention', 'plumbing'),
    '<paths>': ('PS3.10 files to send', 'PS3.10 Table 7.1-1', '', 'plumbing'),
    '--recursive': ('', '', '', 'plumbing'),
    '--verify': ('C-ECHO before sending', 'PS3.4 Annex A', '', 'plumbing'),
    '--retry': ('retry on error or Failure-class status', '', '>= 0', 'plumbing'),
    '--dry-run': ('', '', '', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
    '--timeout': ('ARTIM / socket timeout', 'PS3.8 9.1.2', 'seconds', 'plumbing'),
    '--priority': ('Priority (0000,0700) of C-STORE-RQ', 'PS3.7 Table 9.3-1', 'LOW 0002H, MEDIUM 0000H, HIGH 0001H = low/medium/high', 'match'),
    '--transfer-syntax': ('Transfer Syntax Name of the proposed Presentation Context', 'PS3.8 7.1.1.13; PS3.6 Table A-1', 'any Table A-1 Transfer Syntax UID or DICOMCore alias; unknown -> usage error', 'match'),
}

CONTRACT['dicom-query'] = {
    '<host>': ('TCP transport address', 'PS3.8 9.1.1', 'host[:port]', 'plumbing'),
    '--port': ('TCP port', 'PS3.8 9.1.1 (well-known 104, registered 11112)', '1-65535; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 Table 6.2-1 VR AE', '<=16 bytes (DICOMNetwork.AETitle)', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 Table 6.2-1 VR AE', 'as --aet; default "ANY-SCP" is a tool convention', 'plumbing'),
    '--level': ('Query/Retrieve Level (0008,0052)', 'PS3.4 Tables C.6.1-1 / C.6.2-1; C.4.1.1.3.1', 'PATIENT, STUDY, SERIES, IMAGE = patient/study/series/image (+ alias instance)', 'wrong -> fixed (help/messages said instance; wire value IMAGE)'),
    '--patient-name': ("Patient's Name (0010,0010) matching key", 'PS3.4 Table C.6-5 R / C.6-1 R; C.2.2.2.4', 'PN; * and ? wild cards', 'match'),
    '--patient-id': ('Patient ID (0010,0020) matching key', 'PS3.4 Table C.6-5 R / C.6-1 U', 'LO', 'match'),
    '--study-date': ('Study Date (0008,0020) matching key', 'PS3.4 Table C.6-5 R; C.2.2.2.5', 'DA single value or range d1-d2, -d1, d1-', 'match'),
    '--study-uid': ('Study Instance UID (0020,000D) unique key', 'PS3.4 Table C.6-5 U; C.4.1.2.1', 'UI (single value / UID list)', 'match'),
    '--series-uid': ('Series Instance UID (0020,000E) unique key', 'PS3.4 Table C.6-3 U; C.4.1.2.1', 'UI', 'match'),
    '--accession-number': ('Accession Number (0008,0050) matching key', 'PS3.4 Table C.6-5 R', 'SH', 'match'),
    '--modality': ('Modalities in Study (0008,0061) at STUDY; Modality (0008,0060) at SERIES', 'PS3.4 Tables C.6-5 O / C.6-3 R; PS3.3 C.7.3.1.1.1', 'Defined Terms via DICOMCore.Modality (unknown warns, --strict-modality rejects)', 'match'),
    '--strict-modality': ('reject a value that is not a Defined Term', 'PS3.3 C.7.3.1.1.1', '', 'plumbing'),
    '--study-description': ('Study Description (0008,1030) matching key', 'PS3.4 Table C.6-5 O; C.2.2.2.4', 'LO; wild cards', 'match'),
    '--referring-physician': ("Referring Physician's Name (0008,0090) matching key", 'PS3.4 Table C.6-5 O', 'PN', 'match'),
    '--format': ('output rendering', '', 'table, json, csv, compact (json/csv keys are "(GGGG,EEEE)" tag strings, not PS3.18 F.2)', 'plumbing'),
    '--timeout': ('ARTIM / socket timeout', 'PS3.8 9.1.2', 'seconds', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
    '--include-parent-keys': ('non-baseline parent-level return keys at SERIES/IMAGE', 'PS3.4 C.4.1.2.1 (forbids them for a baseline SCU)', 'flag', 'extra (documented non-baseline)'),
}

CONTRACT['dicom-retrieve'] = {
    '<host>': ('TCP address of the SCP', 'PS3.8 9.1.2', 'hostname/IP, host[:port]', 'plumbing'),
    '--port': ('DICOM UL port', 'PS3.8 9.1.2', '104 well-known / 11112 registered; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 Table 9-11; PS3.5 Table 6.2-1 VR AE', 'AE <=16 chars', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 Table 9-11; PS3.5 VR AE', 'AE; code default ANY-SCP', 'plumbing'),
    '--study-uid': ('Study Instance UID (0020,000D), unique key, level STUDY', 'PS3.4 Table C.6-5; Table C.6.1-1', 'UI', 'match'),
    '--series-uid': ('Series Instance UID (0020,000E), level SERIES', 'PS3.4 C.4.2.2.1; Table C.6.1-1', 'UI, requires --study-uid', 'match'),
    '--instance-uid': ('SOP Instance UID (0008,0018), level IMAGE', 'PS3.4 Table C.6.1-1; C.4.2.2.1', 'UI, requires study+series; wire level value IMAGE', 'match'),
    '--uid-list': ('several Study Instance UIDs, one request each', 'PS3.4 C.4.2.2.1', 'file, one UID per line', 'plumbing'),
    '--output': ('output directory for Part 10 files', 'PS3.10 7.1', 'path; default .', 'plumbing'),
    '--method': ('C-MOVE / C-GET: Study Root QR IM - MOVE 1.2.840.10008.5.1.4.1.2.2.2 / - GET ...2.2.3', 'PS3.4 Table C.6.2.3-1; C.4.2 / C.4.3', 'c-move, c-get; default c-move', 'match'),
    '--move-dest': ('Move Destination (0000,0600)', 'PS3.7 Table 9.3-9; PS3.4 C.4.2.2.1', 'AE of a Storage SCP; required for c-move', 'match'),
    '--hierarchical': ('output layout study/series (C-GET only)', '—', 'flag', 'plumbing'),
    '--timeout': ('socket timeout', '—', 'seconds; default 60', 'plumbing'),
    '--parallel': ('concurrent uid-list retrievals', '—', 'int >= 1; default 1', 'plumbing'),
    '--transfer-syntax': ('Transfer Syntax proposed for C-GET storage contexts', 'PS3.4 C.4.3.2.1; PS3.6 Table A-1', 'shared TransferSyntax.parse tokens', 'match'),
    '-v, --verbose': ('—', '—', 'flag', 'plumbing'),
    '(priority)': ('Priority (0000,0700) not exposed; engine MEDIUM 0000H', 'PS3.7 Table 9.3-9', 'LOW 0002H / MEDIUM 0000H / HIGH 0001H', 'n/a P-RETRIEVE-PRIORITY'),
    '(extended negotiation)': ('relational-retrieve / Enhanced Multi-Frame Image Conversion not exposed', 'PS3.4 Table C.5-1', 'items 1, 5', 'n/a P-RETRIEVE-EXTNEG'),
}

CONTRACT['dicom-qr'] = {
    '<host>': ('TCP address of the SCP', 'PS3.8 9.1.2', 'hostname/IP, host[:port]', 'plumbing'),
    '--port': ('DICOM UL port', 'PS3.8 9.1.2', '104 well-known / 11112 registered; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 Table 9-11; PS3.5 VR AE', 'AE <=16 chars', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 Table 9-11; PS3.5 VR AE', 'AE; default ANY-SCP', 'plumbing'),
    '--move-dest': ('Move Destination (0000,0600)', 'PS3.7 Table 9.3-9; PS3.4 C.4.2.2.1', 'AE of a Storage SCP; required for c-move', 'match'),
    '--method': ('Study Root QR IM - MOVE / - GET', 'PS3.4 Table C.6.2.3-1', 'c-move, c-get; default c-move', 'match'),
    '--patient-name': ("Patient's Name (0010,0010), R key STUDY level, wild card", 'PS3.4 Table C.6-5; C.2.2.2.4', 'PN with * ?', 'match'),
    '--patient-id': ('Patient ID (0010,0020), R', 'PS3.4 Table C.6-5', 'LO', 'match'),
    '--study-date': ('Study Date (0008,0020), R, range matching', 'PS3.4 Table C.6-5; C.2.2.2.5', 'YYYYMMDD, d1-d2, -d1, d1-', 'match'),
    '--study-uid': ('Study Instance UID (0020,000D), U', 'PS3.4 Table C.6-5', 'UI', 'match'),
    '--accession-number': ('Accession Number (0008,0050), R', 'PS3.4 Table C.6-5', 'SH', 'match'),
    '--modality': ('Modalities in Study (0008,0061), O', 'PS3.4 Table C.6-5; PS3.3 C.7.3.1.1.1', 'CS Defined Terms (shared ModalityOptionValidator)', 'match'),
    '--strict-modality': ('—', '—', 'flag', 'plumbing'),
    '--study-description': ('Study Description (0008,1030), O, wild card', 'PS3.4 Table C.6-5; C.2.2.2.4', 'LO with * ?', 'match'),
    '-o, --output': ('output directory', 'PS3.10', 'path; default .', 'plumbing'),
    '--hierarchical': ('output layout <output>/<StudyInstanceUID>/ (C-GET only)', '—', 'flag', 'plumbing'),
    '--interactive': ('mode', '—', 'exactly one of interactive/auto/review', 'plumbing'),
    '--auto': ('mode', '—', 'flag', 'plumbing'),
    '--review': ('mode', '—', 'flag', 'plumbing'),
    '--save-state': ('state file', '—', 'path', 'plumbing'),
    '--timeout': ('socket timeout', '—', 'seconds; default 60', 'plumbing'),
    '--parallel': ('declared, never read (sequential)', '—', 'int; default 1', 'extra P-QR-PARALLEL'),
    '--validate': ('Part 10 read of received files', 'PS3.10', 'flag', 'plumbing'),
    '--transfer-syntax': ('Transfer Syntax proposed for C-GET storage contexts', 'PS3.4 C.4.3.2.1; PS3.6 Table A-1', 'shared TransferSyntax.parse tokens', 'match'),
    '--verbose': ('—', '—', 'flag', 'plumbing'),
    '--include-parent-keys': ('parent-level return keys (no effect at STUDY)', 'PS3.4 C.4.1.1.3.1', 'flag', 'plumbing'),
    'resume -s, --state': ('state file', '—', 'path', 'plumbing'),
    'resume --timeout': ('socket timeout (new, additive)', '—', 'seconds; default 60', 'plumbing'),
    'resume --verbose': ('—', '—', 'flag', 'plumbing'),
    '(level)': ('Query/Retrieve Level always STUDY', 'PS3.4 Table C.6.1-1', 'STUDY', 'match'),
    '(resume: Instance Availability / Retrieve AE Title)': ('(0008,0056) / (0008,0054) not used; resume retrieves from the saved host', 'PS3.4 Table C.6-5; PS3.3 C.4.23', '—', 'n/a'),
}

CONTRACT['dicom-mwl'] = {
    '<host>': ('TCP transport address', 'PS3.8 9.1.1', 'host[:port]', 'plumbing'),
    '--port': ('TCP port', 'PS3.8 9.1.1 (well-known 104; 11112 IANA registered)', '1-65535; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 Table 6.2-1 VR AE', '<=16 bytes (DICOMNetwork.AETitle)', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 Table 6.2-1 VR AE', 'as --aet; default "ANY-SCP" tool convention', 'plumbing'),
    '--date': ('Scheduled Procedure Step Start Date (0040,0002), R key', 'PS3.4 Table K.6-1 row 4; C.2.2.2.5.1; PS3.5 Table 6.2-1 DA', 'YYYYMMDD | D1-D2 | D1- | -D2; today/tomorrow shorthands', 'match'),
    '--time': ('Scheduled Procedure Step Start Time (0040,0003), R key', 'PS3.4 Table K.6-1 row 5 (combined date-time remark); C.2.2.2.5.2/.4; PS3.5 Table 6.2-1 TM', 'HH|HHMM|HHMMSS[.FFFFFF] | T1-T2 | T1- | -T2, never across midnight', 'match (citation fixed)'),
    '--station': ('Scheduled Station AE Title (0040,0001), R key', 'PS3.4 Table K.6-1 row 3 (Single Value Matching only); PS3.5 VR AE', 'AE Title <=16 bytes', 'match'),
    '--patient': ("Patient's Name (0010,0010), R key", 'PS3.4 Table K.6-1 row 86', 'PN, Single Value or Wild Card (*/?)', 'match'),
    '--patient-id': ('Patient ID (0010,0020), R key', 'PS3.4 Table K.6-1 row 87', 'LO, Single Value Matching', 'match'),
    '--modality': ('Modality (0008,0060), R key', 'PS3.4 Table K.6-1 row 6; PS3.3 C.7.3.1.1.1', 'Defined Terms (DICOMCore.ModalityOptionValidator)', 'match'),
    '--strict-modality': ('reject non-Defined-Term modality', 'PS3.3 C.7.3.1.1.1', 'flag', 'plumbing'),
    '--sps-status': ('Scheduled Procedure Step Status (0040,0020), O key type 3', 'PS3.4 Table K.6-1 row 35; PS3.3 Table C.4-10 Defined Terms', 'SCHEDULED | ARRIVED | READY | STARTED | DEPARTED (other values sent with a warning)', 'wrong (help listed PPS words) -> fixed'),
    '--accession-number': ('Accession Number (0008,0050), O key type 2', 'PS3.4 Table K.6-1 row 64', 'SH', 'match'),
    '--performing-physician': ("Scheduled Performing Physician's Name (0040,0006), R key type 2", 'PS3.4 Table K.6-1 row 7', 'PN, Single Value or Wild Card', 'match'),
    '--specific-character-set': ('Specific Character Set (0008,0005) of the Identifier', 'PS3.4 Table K.6-1a; PS3.5 6.1.2 / Table 6.1-1', 'Defined Terms; auto-chosen when absent', 'match'),
    '--timeout': ('ARTIM / socket timeout', 'PS3.8 9.1.2', 'seconds; default 60', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
    '--json': ('JSON rendering; 28/38 keys are PS3.6 keywords', 'PS3.6 Table 6-1', 'see P-MWL-JSON-KEYS', 'plumbing'),
}

CONTRACT['dicom-mpps'] = {
    '<host>': ('TCP transport address', 'PS3.8 9.1.1', 'host[:port]', 'plumbing'),
    '--port': ('TCP port', 'PS3.8 9.1.1 (well-known 104; 11112 IANA registered)', '1-65535; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 Table 6.2-1 VR AE', '<=16 bytes (DICOMNetwork.AETitle)', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 Table 6.2-1 VR AE', 'as --aet; default "ANY-SCP" tool convention', 'plumbing'),
    '--timeout': ('ARTIM / socket timeout', 'PS3.8 9.1.2', 'seconds; default 60', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
    '--specific-character-set': ('Specific Character Set (0008,0005)', 'PS3.4 Table F.7.2-1 row 1 (1C/1C); PS3.5 6.1.2', 'Defined Terms; auto-chosen when absent', 'match'),
    '--strict-modality': ('reject non-Defined-Term modality', 'PS3.3 C.7.3.1.1.1', 'flag', 'plumbing'),
    '--study-uid': ('Study Instance UID (0020,000D) in (0040,0270) [create]; Performed Series pairing [update]', 'PS3.4 Table F.7.2-1 row 4 (1/1)', 'UI', 'match'),
    '--status': ('Performed Procedure Step Status (0040,0252)', 'PS3.3 Table C.4-14; PS3.4 F.7.2.1.2 (create: IN PROGRESS only), F.7.2.2.2 (update: COMPLETED|DISCONTINUED, final)', 'IN PROGRESS | COMPLETED | DISCONTINUED (case-insensitive, space optional or _)', 'match'),
    '--modality': ('Modality (0008,0060)', 'PS3.4 Table F.7.2-1 row 105 (1/1); PS3.3 C.7.3.1.1.1', 'Defined Term; now required for create', 'missing (empty Type 1) -> fixed'),
    '--patient-name': ("Patient's Name (0010,0010)", 'PS3.4 Table F.7.2-1 row 32 (2/2)', 'PN', 'match'),
    '--patient-id': ('Patient ID (0010,0020)', 'PS3.4 Table F.7.2-1 row 33 (2/2)', 'LO', 'match'),
    '--patient-birth-date': ("Patient's Birth Date (0010,0030)", 'PS3.4 Table F.7.2-1 row 45 (2/2); PS3.5 Table 6.2-1 DA', 'YYYYMMDD (now validated)', 'match'),
    '--patient-sex': ("Patient's Sex (0010,0040)", 'PS3.4 Table F.7.2-1 row 46 (2/2); PS3.3 Table C.2-3', 'M | F | O (now validated)', 'match'),
    '--sps-id': ('Scheduled Procedure Step ID (0040,0009) in (0040,0270)', 'PS3.4 Table F.7.2-1 row 27 (2/2)', 'SH', 'match'),
    '--accession-number': ('Accession Number (0008,0050) in (0040,0270)', 'PS3.4 Table F.7.2-1 row 8 (2/2)', 'SH', 'match'),
    '--requested-procedure-id': ('Requested Procedure ID (0040,1001) in (0040,0270)', 'PS3.4 Table F.7.2-1 row 23 (2/2)', 'SH', 'match'),
    '--requested-procedure-description': ('Requested Procedure Description (0032,1060) in (0040,0270)', 'PS3.4 Table F.7.2-1 row 26 (2/2)', 'LO', 'match'),
    '--sps-description': ('Scheduled Procedure Step Description (0040,0007) in (0040,0270)', 'PS3.4 Table F.7.2-1 row 28 (2/2)', 'LO', 'match'),
    '--referenced-study-uid': ('Referenced SOP Instance UID (0008,1155) in Referenced Study Sequence (0008,1110)', 'PS3.4 Table F.7.2-1 rows 5-7', 'UI', 'match'),
    '--study-id': ('Study ID (0020,0010)', 'PS3.4 Table F.7.2-1 row 106 (2/2)', 'SH', 'match'),
    '--station-name': ('Performed Station Name (0040,0242)', 'PS3.4 Table F.7.2-1 row 88 (2/2)', 'SH', 'match'),
    '--performed-location': ('Performed Location (0040,0243)', 'PS3.4 Table F.7.2-1 row 89 (2/2)', 'SH', 'match'),
    '--procedure-step-id': ('Performed Procedure Step ID (0040,0253)', 'PS3.4 Table F.7.2-1 row 86 (1/1)', 'SH; engine default "1"', 'match'),
    '--procedure-step-description': ('Performed Procedure Step Description (0040,0254)', 'PS3.4 Table F.7.2-1 row 93 (2/2)', 'LO', 'match'),
    '--performing-physician': ("Performing Physician's Name (0008,1050) in Performed Series item", 'PS3.4 Table F.7.2-1 row 111 (2/2)', 'PN', 'match'),
    '--mpps-uid': ('Requested SOP Instance UID of the N-SET', 'PS3.7 Table 10.3-5; 10.1.5.1.4', 'UI', 'match'),
    '--series-uid': ('Series Instance UID (0020,000E) of the Performed Series item', 'PS3.4 Table F.7.2-1 row 114 (1/1)', 'UI', 'match'),
    '--image-uid': ('Referenced SOP Instance UID (0008,1155) in Referenced Image Sequence (0008,1140)', 'PS3.4 Table F.7.2-1 rows 118-120', 'UI, repeatable; now requires --study-uid and --series-uid', 'wrong (silently dropped) -> fixed'),
    '--sop-class-uid': ('Referenced SOP Class UID (0008,1150)', 'PS3.4 Table F.7.2-1 row 119 (1/1); PS3.6 Table A-1', 'registered SOP Class UID; engine default Secondary Capture (warned)', 'match'),
    '--protocol-name': ('Protocol Name (0018,1030)', 'PS3.4 Table F.7.2-1 row 112 (1/1)', 'LO; engine default UNSPECIFIED', 'match'),
    '--series-description': ('Series Description (0008,103E)', 'PS3.4 Table F.7.2-1 row 115 (2/2)', 'LO', 'match'),
    '--operator-name': ("Operators' Name (0008,1070)", 'PS3.4 Table F.7.2-1 row 113 (2/2)', 'PN', 'match'),
    '--legacy-nset-scheduled-attributes': ('Scheduled Step Attributes Sequence (0040,0270) in N-SET', 'PS3.4 Table F.7.2-1 row 3 (N-SET: Not allowed)', 'opt-in flag for non-conformant SCPs', 'match'),
    '--discontinuation-reason': ('PPS Discontinuation Reason Code Sequence (0040,0281)', 'PS3.4 Table F.7.2-1 row 102 (3/3, macro F.7.2-1c); PS3.16 CID 9300 / CID 9301 / Table D-1', 'CODE|SCHEME|MEANING, only with DISCONTINUED', 'wrong examples -> fixed'),
}
