"""Per-tool parameter-contract rows for Scripts/diff_cli.py: option -> (DICOM concept, 2026a reference,
allowed values / note, verdict). One block per tool, added as each tool is verified; the same rows appear
as the Input contract tables in DICOMCLI_STANDARD_IMPLEMENTATION.md."""
CONTRACT = {}

CONTRACT['dicom-echo'] = {
    '<host>': ('TCP transport address', 'PS3.8 9.1.1', 'host[:port]', 'plumbing'),
    '--port': ('TCP port', 'PS3.8 9.1.1 (well-known 104, registered 11112)', '1-65535; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 Table 6.2-1 VR AE', '<=16 bytes, no backslash/control, not all spaces (DICOMNetwork.AETitle)', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 Table 6.2-1 VR AE', 'as --aet; default "ANY-SCP" is a tool convention', 'plumbing'),
    '--count': ('number of C-ECHO operations', 'PS3.7 9.1.5', '> 0', 'plumbing'),
    '--timeout': ('ARTIM / socket timeout', 'PS3.8 9.1.2', 'seconds', 'plumbing'),
    '--stats': ('round-trip statistics', '', '', 'plumbing'),
    '--diagnose': ('connectivity probe; prints PS3.7 Tables D.3-1 / D.3-3 identification', 'PS3.7 Annex D.3', '', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
}

CONTRACT['dicom-send'] = {
    '<host>': ('TCP transport address', 'PS3.8 9.1.1', 'host[:port]', 'plumbing'),
    '--port': ('TCP port', 'PS3.8 9.1.1 (well-known 104, registered 11112)', '1-65535; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 Table 6.2-1 VR AE', '<=16 bytes (DICOMNetwork.AETitle)', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 Table 6.2-1 VR AE', 'as --aet; default "ANY-SCP" is a tool convention', 'plumbing'),
    '<paths>': ('PS3.10 files to send', 'PS3.10 Table 7.1-1', '', 'plumbing'),
    '--recursive': ('', '', '', 'plumbing'),
    '--verify': ('C-ECHO before sending', 'PS3.4 Annex A', '', 'plumbing'),
    '--retry': ('retry on error or Failure-class status', '', '>= 0', 'plumbing'),
    '--dry-run': ('', '', '', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
    '--timeout': ('ARTIM / socket timeout', 'PS3.8 9.1.2', 'seconds', 'plumbing'),
    '--priority': ('Priority (0000,0700) of C-STORE-RQ', 'PS3.7 Table 9.3-1', 'LOW 0002H, MEDIUM 0000H, HIGH 0001H = low/medium/high', 'match'),
    '--transfer-syntax': ('Transfer Syntax Name of the proposed Presentation Context', 'PS3.8 7.1.1.13; PS3.6 Table A-1', 'any Table A-1 Transfer Syntax UID or DICOMCore alias; unknown -> usage error', 'match'),
}

CONTRACT['dicom-query'] = {
    '<host>': ('TCP transport address', 'PS3.8 9.1.1', 'host[:port]', 'plumbing'),
    '--port': ('TCP port', 'PS3.8 9.1.1 (well-known 104, registered 11112)', '1-65535; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 Table 6.2-1 VR AE', '<=16 bytes (DICOMNetwork.AETitle)', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 Table 6.2-1 VR AE', 'as --aet; default "ANY-SCP" is a tool convention', 'plumbing'),
    '--level': ('Query/Retrieve Level (0008,0052)', 'PS3.4 Tables C.6.1-1 / C.6.2-1; C.4.1.1.3.1', 'PATIENT, STUDY, SERIES, IMAGE = patient/study/series/image (+ alias instance)', 'wrong -> fixed (help/messages said instance; wire value IMAGE)'),
    '--patient-name': ("Patient's Name (0010,0010) matching key", 'PS3.4 Table C.6-5 R / C.6-1 R; C.2.2.2.4', 'PN; * and ? wild cards', 'match'),
    '--patient-id': ('Patient ID (0010,0020) matching key', 'PS3.4 Table C.6-5 R / C.6-1 U', 'LO', 'match'),
    '--study-date': ('Study Date (0008,0020) matching key', 'PS3.4 Table C.6-5 R; C.2.2.2.5', 'DA single value or range d1-d2, -d1, d1-', 'match'),
    '--study-uid': ('Study Instance UID (0020,000D) unique key', 'PS3.4 Table C.6-5 U; C.4.1.2.1', 'UI (single value / UID list)', 'match'),
    '--series-uid': ('Series Instance UID (0020,000E) unique key', 'PS3.4 Table C.6-3 U; C.4.1.2.1', 'UI', 'match'),
    '--accession-number': ('Accession Number (0008,0050) matching key', 'PS3.4 Table C.6-5 R', 'SH', 'match'),
    '--modality': ('Modalities in Study (0008,0061) at STUDY; Modality (0008,0060) at SERIES', 'PS3.4 Tables C.6-5 O / C.6-3 R; PS3.3 C.7.3.1.1.1', 'Defined Terms via DICOMCore.Modality (unknown warns, --strict-modality rejects)', 'match'),
    '--strict-modality': ('reject a value that is not a Defined Term', 'PS3.3 C.7.3.1.1.1', '', 'plumbing'),
    '--study-description': ('Study Description (0008,1030) matching key', 'PS3.4 Table C.6-5 O; C.2.2.2.4', 'LO; wild cards', 'match'),
    '--referring-physician': ("Referring Physician's Name (0008,0090) matching key", 'PS3.4 Table C.6-5 O', 'PN', 'match'),
    '--format': ('output rendering', '', 'table, json, csv, compact (json/csv keys are "(GGGG,EEEE)" tag strings, not PS3.18 F.2)', 'plumbing'),
    '--timeout': ('ARTIM / socket timeout', 'PS3.8 9.1.2', 'seconds', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
    '--include-parent-keys': ('non-baseline parent-level return keys at SERIES/IMAGE', 'PS3.4 C.4.1.2.1 (forbids them for a baseline SCU)', 'flag', 'extra (documented non-baseline)'),
}

CONTRACT['dicom-retrieve'] = {
    '<host>': ('TCP address of the SCP', 'PS3.8 9.1.2', 'hostname/IP, host[:port]', 'plumbing'),
    '--port': ('DICOM UL port', 'PS3.8 9.1.2', '104 well-known / 11112 registered; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 Table 9-11; PS3.5 Table 6.2-1 VR AE', 'AE <=16 chars', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 Table 9-11; PS3.5 VR AE', 'AE; code default ANY-SCP', 'plumbing'),
    '--study-uid': ('Study Instance UID (0020,000D), unique key, level STUDY', 'PS3.4 Table C.6-5; Table C.6.1-1', 'UI', 'match'),
    '--series-uid': ('Series Instance UID (0020,000E), level SERIES', 'PS3.4 C.4.2.2.1; Table C.6.1-1', 'UI, requires --study-uid', 'match'),
    '--instance-uid': ('SOP Instance UID (0008,0018), level IMAGE', 'PS3.4 Table C.6.1-1; C.4.2.2.1', 'UI, requires study+series; wire level value IMAGE', 'match'),
    '--uid-list': ('several Study Instance UIDs, one request each', 'PS3.4 C.4.2.2.1', 'file, one UID per line', 'plumbing'),
    '--output': ('output directory for Part 10 files', 'PS3.10 7.1', 'path; default .', 'plumbing'),
    '--method': ('C-MOVE / C-GET: Study Root QR IM - MOVE 1.2.840.10008.5.1.4.1.2.2.2 / - GET ...2.2.3', 'PS3.4 Table C.6.2.3-1; C.4.2 / C.4.3', 'c-move, c-get; default c-move', 'match'),
    '--move-dest': ('Move Destination (0000,0600)', 'PS3.7 Table 9.3-9; PS3.4 C.4.2.2.1', 'AE of a Storage SCP; required for c-move', 'match'),
    '--hierarchical': ('output layout study/series (C-GET only)', '—', 'flag', 'plumbing'),
    '--timeout': ('socket timeout', '—', 'seconds; default 60', 'plumbing'),
    '--parallel': ('concurrent uid-list retrievals', '—', 'int >= 1; default 1', 'plumbing'),
    '--transfer-syntax': ('Transfer Syntax proposed for C-GET storage contexts', 'PS3.4 C.4.3.2.1; PS3.6 Table A-1', 'shared TransferSyntax.parse tokens', 'match'),
    '-v, --verbose': ('—', '—', 'flag', 'plumbing'),
    '(priority)': ('Priority (0000,0700) not exposed; engine MEDIUM 0000H', 'PS3.7 Table 9.3-9', 'LOW 0002H / MEDIUM 0000H / HIGH 0001H', 'n/a P-RETRIEVE-PRIORITY'),
    '(extended negotiation)': ('relational-retrieve / Enhanced Multi-Frame Image Conversion not exposed', 'PS3.4 Table C.5-1', 'items 1, 5', 'n/a P-RETRIEVE-EXTNEG'),
}

CONTRACT['dicom-qr'] = {
    '<host>': ('TCP address of the SCP', 'PS3.8 9.1.2', 'hostname/IP, host[:port]', 'plumbing'),
    '--port': ('DICOM UL port', 'PS3.8 9.1.2', '104 well-known / 11112 registered; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 Table 9-11; PS3.5 VR AE', 'AE <=16 chars', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 Table 9-11; PS3.5 VR AE', 'AE; default ANY-SCP', 'plumbing'),
    '--move-dest': ('Move Destination (0000,0600)', 'PS3.7 Table 9.3-9; PS3.4 C.4.2.2.1', 'AE of a Storage SCP; required for c-move', 'match'),
    '--method': ('Study Root QR IM - MOVE / - GET', 'PS3.4 Table C.6.2.3-1', 'c-move, c-get; default c-move', 'match'),
    '--patient-name': ("Patient's Name (0010,0010), R key STUDY level, wild card", 'PS3.4 Table C.6-5; C.2.2.2.4', 'PN with * ?', 'match'),
    '--patient-id': ('Patient ID (0010,0020), R', 'PS3.4 Table C.6-5', 'LO', 'match'),
    '--study-date': ('Study Date (0008,0020), R, range matching', 'PS3.4 Table C.6-5; C.2.2.2.5', 'YYYYMMDD, d1-d2, -d1, d1-', 'match'),
    '--study-uid': ('Study Instance UID (0020,000D), U', 'PS3.4 Table C.6-5', 'UI', 'match'),
    '--accession-number': ('Accession Number (0008,0050), R', 'PS3.4 Table C.6-5', 'SH', 'match'),
    '--modality': ('Modalities in Study (0008,0061), O', 'PS3.4 Table C.6-5; PS3.3 C.7.3.1.1.1', 'CS Defined Terms (shared ModalityOptionValidator)', 'match'),
    '--strict-modality': ('—', '—', 'flag', 'plumbing'),
    '--study-description': ('Study Description (0008,1030), O, wild card', 'PS3.4 Table C.6-5; C.2.2.2.4', 'LO with * ?', 'match'),
    '-o, --output': ('output directory', 'PS3.10', 'path; default .', 'plumbing'),
    '--hierarchical': ('output layout <output>/<StudyInstanceUID>/ (C-GET only)', '—', 'flag', 'plumbing'),
    '--interactive': ('mode', '—', 'exactly one of interactive/auto/review', 'plumbing'),
    '--auto': ('mode', '—', 'flag', 'plumbing'),
    '--review': ('mode', '—', 'flag', 'plumbing'),
    '--save-state': ('state file', '—', 'path', 'plumbing'),
    '--timeout': ('socket timeout', '—', 'seconds; default 60', 'plumbing'),
    '--parallel': ('declared, never read (sequential)', '—', 'int; default 1', 'extra P-QR-PARALLEL'),
    '--validate': ('Part 10 read of received files', 'PS3.10', 'flag', 'plumbing'),
    '--transfer-syntax': ('Transfer Syntax proposed for C-GET storage contexts', 'PS3.4 C.4.3.2.1; PS3.6 Table A-1', 'shared TransferSyntax.parse tokens', 'match'),
    '--verbose': ('—', '—', 'flag', 'plumbing'),
    '--include-parent-keys': ('parent-level return keys (no effect at STUDY)', 'PS3.4 C.4.1.1.3.1', 'flag', 'plumbing'),
    'resume -s, --state': ('state file', '—', 'path', 'plumbing'),
    'resume --timeout': ('socket timeout (new, additive)', '—', 'seconds; default 60', 'plumbing'),
    'resume --verbose': ('—', '—', 'flag', 'plumbing'),
    '(level)': ('Query/Retrieve Level always STUDY', 'PS3.4 Table C.6.1-1', 'STUDY', 'match'),
    '(resume: Instance Availability / Retrieve AE Title)': ('(0008,0056) / (0008,0054) not used; resume retrieves from the saved host', 'PS3.4 Table C.6-5; PS3.3 C.4.23', '—', 'n/a'),
}

CONTRACT['dicom-mwl'] = {
    '<host>': ('TCP transport address', 'PS3.8 9.1.1', 'host[:port]', 'plumbing'),
    '--port': ('TCP port', 'PS3.8 9.1.1 (well-known 104; 11112 IANA registered)', '1-65535; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 Table 6.2-1 VR AE', '<=16 bytes (DICOMNetwork.AETitle)', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 Table 6.2-1 VR AE', 'as --aet; default "ANY-SCP" tool convention', 'plumbing'),
    '--date': ('Scheduled Procedure Step Start Date (0040,0002), R key', 'PS3.4 Table K.6-1 row 4; C.2.2.2.5.1; PS3.5 Table 6.2-1 DA', 'YYYYMMDD | D1-D2 | D1- | -D2; today/tomorrow shorthands', 'match'),
    '--time': ('Scheduled Procedure Step Start Time (0040,0003), R key', 'PS3.4 Table K.6-1 row 5 (combined date-time remark); C.2.2.2.5.2/.4; PS3.5 Table 6.2-1 TM', 'HH|HHMM|HHMMSS[.FFFFFF] | T1-T2 | T1- | -T2, never across midnight', 'match (citation fixed)'),
    '--station': ('Scheduled Station AE Title (0040,0001), R key', 'PS3.4 Table K.6-1 row 3 (Single Value Matching only); PS3.5 VR AE', 'AE Title <=16 bytes', 'match'),
    '--patient': ("Patient's Name (0010,0010), R key", 'PS3.4 Table K.6-1 row 86', 'PN, Single Value or Wild Card (*/?)', 'match'),
    '--patient-id': ('Patient ID (0010,0020), R key', 'PS3.4 Table K.6-1 row 87', 'LO, Single Value Matching', 'match'),
    '--modality': ('Modality (0008,0060), R key', 'PS3.4 Table K.6-1 row 6; PS3.3 C.7.3.1.1.1', 'Defined Terms (DICOMCore.ModalityOptionValidator)', 'match'),
    '--strict-modality': ('reject non-Defined-Term modality', 'PS3.3 C.7.3.1.1.1', 'flag', 'plumbing'),
    '--sps-status': ('Scheduled Procedure Step Status (0040,0020), O key type 3', 'PS3.4 Table K.6-1 row 35; PS3.3 Table C.4-10 Defined Terms', 'SCHEDULED | ARRIVED | READY | STARTED | DEPARTED (other values sent with a warning)', 'wrong (help listed PPS words) -> fixed'),
    '--accession-number': ('Accession Number (0008,0050), O key type 2', 'PS3.4 Table K.6-1 row 64', 'SH', 'match'),
    '--performing-physician': ("Scheduled Performing Physician's Name (0040,0006), R key type 2", 'PS3.4 Table K.6-1 row 7', 'PN, Single Value or Wild Card', 'match'),
    '--specific-character-set': ('Specific Character Set (0008,0005) of the Identifier', 'PS3.4 Table K.6-1a; PS3.5 6.1.2 / Table 6.1-1', 'Defined Terms; auto-chosen when absent', 'match'),
    '--timeout': ('ARTIM / socket timeout', 'PS3.8 9.1.2', 'seconds; default 60', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
    '--json': ('JSON rendering; 28/38 keys are PS3.6 keywords', 'PS3.6 Table 6-1', 'see P-MWL-JSON-KEYS', 'plumbing'),
}

CONTRACT['dicom-mpps'] = {
    '<host>': ('TCP transport address', 'PS3.8 9.1.1', 'host[:port]', 'plumbing'),
    '--port': ('TCP port', 'PS3.8 9.1.1 (well-known 104; 11112 IANA registered)', '1-65535; code default 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 Table 6.2-1 VR AE', '<=16 bytes (DICOMNetwork.AETitle)', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 Table 6.2-1 VR AE', 'as --aet; default "ANY-SCP" tool convention', 'plumbing'),
    '--timeout': ('ARTIM / socket timeout', 'PS3.8 9.1.2', 'seconds; default 60', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
    '--specific-character-set': ('Specific Character Set (0008,0005)', 'PS3.4 Table F.7.2-1 row 1 (1C/1C); PS3.5 6.1.2', 'Defined Terms; auto-chosen when absent', 'match'),
    '--strict-modality': ('reject non-Defined-Term modality', 'PS3.3 C.7.3.1.1.1', 'flag', 'plumbing'),
    '--study-uid': ('Study Instance UID (0020,000D) in (0040,0270) [create]; Performed Series pairing [update]', 'PS3.4 Table F.7.2-1 row 4 (1/1)', 'UI', 'match'),
    '--status': ('Performed Procedure Step Status (0040,0252)', 'PS3.3 Table C.4-14; PS3.4 F.7.2.1.2 (create: IN PROGRESS only), F.7.2.2.2 (update: COMPLETED|DISCONTINUED, final)', 'IN PROGRESS | COMPLETED | DISCONTINUED (case-insensitive, space optional or _)', 'match'),
    '--modality': ('Modality (0008,0060)', 'PS3.4 Table F.7.2-1 row 105 (1/1); PS3.3 C.7.3.1.1.1', 'Defined Term; now required for create', 'missing (empty Type 1) -> fixed'),
    '--patient-name': ("Patient's Name (0010,0010)", 'PS3.4 Table F.7.2-1 row 32 (2/2)', 'PN', 'match'),
    '--patient-id': ('Patient ID (0010,0020)', 'PS3.4 Table F.7.2-1 row 33 (2/2)', 'LO', 'match'),
    '--patient-birth-date': ("Patient's Birth Date (0010,0030)", 'PS3.4 Table F.7.2-1 row 45 (2/2); PS3.5 Table 6.2-1 DA', 'YYYYMMDD (now validated)', 'match'),
    '--patient-sex': ("Patient's Sex (0010,0040)", 'PS3.4 Table F.7.2-1 row 46 (2/2); PS3.3 Table C.2-3', 'M | F | O (now validated)', 'match'),
    '--sps-id': ('Scheduled Procedure Step ID (0040,0009) in (0040,0270)', 'PS3.4 Table F.7.2-1 row 27 (2/2)', 'SH', 'match'),
    '--accession-number': ('Accession Number (0008,0050) in (0040,0270)', 'PS3.4 Table F.7.2-1 row 8 (2/2)', 'SH', 'match'),
    '--requested-procedure-id': ('Requested Procedure ID (0040,1001) in (0040,0270)', 'PS3.4 Table F.7.2-1 row 23 (2/2)', 'SH', 'match'),
    '--requested-procedure-description': ('Requested Procedure Description (0032,1060) in (0040,0270)', 'PS3.4 Table F.7.2-1 row 26 (2/2)', 'LO', 'match'),
    '--sps-description': ('Scheduled Procedure Step Description (0040,0007) in (0040,0270)', 'PS3.4 Table F.7.2-1 row 28 (2/2)', 'LO', 'match'),
    '--referenced-study-uid': ('Referenced SOP Instance UID (0008,1155) in Referenced Study Sequence (0008,1110)', 'PS3.4 Table F.7.2-1 rows 5-7', 'UI', 'match'),
    '--study-id': ('Study ID (0020,0010)', 'PS3.4 Table F.7.2-1 row 106 (2/2)', 'SH', 'match'),
    '--station-name': ('Performed Station Name (0040,0242)', 'PS3.4 Table F.7.2-1 row 88 (2/2)', 'SH', 'match'),
    '--performed-location': ('Performed Location (0040,0243)', 'PS3.4 Table F.7.2-1 row 89 (2/2)', 'SH', 'match'),
    '--procedure-step-id': ('Performed Procedure Step ID (0040,0253)', 'PS3.4 Table F.7.2-1 row 86 (1/1)', 'SH; engine default "1"', 'match'),
    '--procedure-step-description': ('Performed Procedure Step Description (0040,0254)', 'PS3.4 Table F.7.2-1 row 93 (2/2)', 'LO', 'match'),
    '--performing-physician': ("Performing Physician's Name (0008,1050) in Performed Series item", 'PS3.4 Table F.7.2-1 row 111 (2/2)', 'PN', 'match'),
    '--mpps-uid': ('Requested SOP Instance UID of the N-SET', 'PS3.7 Table 10.3-5; 10.1.5.1.4', 'UI', 'match'),
    '--series-uid': ('Series Instance UID (0020,000E) of the Performed Series item', 'PS3.4 Table F.7.2-1 row 114 (1/1)', 'UI', 'match'),
    '--image-uid': ('Referenced SOP Instance UID (0008,1155) in Referenced Image Sequence (0008,1140)', 'PS3.4 Table F.7.2-1 rows 118-120', 'UI, repeatable; now requires --study-uid and --series-uid', 'wrong (silently dropped) -> fixed'),
    '--sop-class-uid': ('Referenced SOP Class UID (0008,1150)', 'PS3.4 Table F.7.2-1 row 119 (1/1); PS3.6 Table A-1', 'registered SOP Class UID; engine default Secondary Capture (warned)', 'match'),
    '--protocol-name': ('Protocol Name (0018,1030)', 'PS3.4 Table F.7.2-1 row 112 (1/1)', 'LO; engine default UNSPECIFIED', 'match'),
    '--series-description': ('Series Description (0008,103E)', 'PS3.4 Table F.7.2-1 row 115 (2/2)', 'LO', 'match'),
    '--operator-name': ("Operators' Name (0008,1070)", 'PS3.4 Table F.7.2-1 row 113 (2/2)', 'PN', 'match'),
    '--legacy-nset-scheduled-attributes': ('Scheduled Step Attributes Sequence (0040,0270) in N-SET', 'PS3.4 Table F.7.2-1 row 3 (N-SET: Not allowed)', 'opt-in flag for non-conformant SCPs', 'match'),
    '--discontinuation-reason': ('PPS Discontinuation Reason Code Sequence (0040,0281)', 'PS3.4 Table F.7.2-1 row 102 (3/3, macro F.7.2-1c); PS3.16 CID 9300 / CID 9301 / Table D-1', 'CODE|SCHEME|MEANING, only with DISCONTINUED', 'wrong examples -> fixed'),
}

CONTRACT['dicom-print'] = {
    '<url>': ('TCP address of the Print SCP (pacs://host[:port])', 'PS3.8 9.1.1 (well-known 104, registered 11112)', 'host[:port]; code default port 11112', 'plumbing'),
    '--aet': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 Table 6.2-1 VR AE', 'AE <=16 chars', 'plumbing'),
    '--called-aet': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 Table 6.2-1 VR AE', 'AE; default "ANY-SCP" is a tool convention', 'plumbing'),
    '--timeout': ('ARTIM / socket timeout', 'PS3.8 9.1.2', 'seconds (status/job 30, send 60)', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
    '--format': ('output rendering', '', 'text, json', 'plumbing'),
    '<paths>': ('PS3.10 files to print', 'PS3.10 7.1', '', 'plumbing'),
    '--copies': ('Number of Copies (2000,0010)', 'PS3.3 Table C.13-1; PS3.4 Table H.4-2 U/M', 'IS; std default none (SCP); code 1, >=1', 'match'),
    '--film-size': ('Film Size ID (2010,0050)', 'PS3.3 Table C.13-3 (12 Defined Terms)', '8INX10IN..A3 = 12 tokens (8x10..a3); term accepted as alias; std default none; code 14x17', 'wrong -> fixed (help listed 9 of 12, named no term)'),
    '--orientation': ('Film Orientation (2010,0040)', 'PS3.3 Table C.13-3', 'PORTRAIT, LANDSCAPE = portrait/landscape; std default none; code portrait', 'match'),
    '--priority': ('Print Priority (2000,0020)', 'PS3.3 Table C.13-1 (Enumerated Values)', 'HIGH, MED, LOW = high/medium/low; std default none; code medium', 'match (help now names MED)'),
    '--layout': ('Image Display Format (2010,0010)', 'PS3.3 Table C.13-3 (Enumerated Values)', 'STANDARD\\C,R, ROW\\.., COL\\.., SLIDE, SUPERSLIDE, CUSTOM\\i all accepted; RxC grid sent as STANDARD\\C,R; std default none; code auto', 'match (help listed 2 of 6 forms -> fixed)'),
    '--template': ('layout preset (Image Display Format + Film Size ID + Film Orientation)', 'PS3.3 Table C.13-3', 'single, comparison, grid, multi-phase', 'extra (tool convenience)'),
    '--medium': ('Medium Type (2000,0030)', 'PS3.3 Table C.13-1 (5 Defined Terms)', 'PAPER, CLEAR FILM, BLUE FILM, MAMMO CLEAR FILM, MAMMO BLUE FILM; std default none; code paper', 'missing -> fixed (mammo-clear-film, mammo-blue-film added)'),
    '--magnification': ('Magnification Type (2010,0060)', 'PS3.3 Table C.13-3', 'REPLICATE, BILINEAR, CUBIC, NONE; std default none; code replicate', 'match'),
    '--film-destination': ('Film Destination (2000,0040)', 'PS3.3 Table C.13-1', 'MAGAZINE, PROCESSOR, BIN_i (i>=1, no maximum); code BIN_1, BIN_2 only; std default none; code processor', 'missing (BIN_i for i>2: engine enum, D-DICOM-PRINT-3)'),
    '--check-status': ('N-GET Printer Status (2110,0010) before printing', 'PS3.3 Table C.13-9; PS3.4 H.4.6', 'FAILURE aborts (exit 1), WARNING warns', 'match'),
    '--verify': ('C-ECHO before printing', 'PS3.4 Annex A', '', 'plumbing'),
    '--color': ('Print Management Meta SOP Class negotiated', 'PS3.4 H.3.2.2.1 / H.3.2.2.2; PS3.6 Table A-1', 'grayscale = 1.2.840.10008.5.1.1.9, color = 1.2.840.10008.5.1.1.18', 'match'),
    '--frame': ('frame of a multi-frame source', '', '>=1', 'plumbing'),
    '--all-frames': ('', '', '', 'plumbing'),
    '--raw': ('send stored values (no VOI/rescale)', 'PS3.3 Table C.13-5', '', 'plumbing'),
    '--window-center': ('VOI window applied before sending', 'PS3.3 C.11.2', '', 'plumbing'),
    '--window-width': ('VOI window applied before sending', 'PS3.3 C.11.2', '', 'plumbing'),
    '--bit-depth': ('Bits Stored (0028,0101) of the Basic Grayscale Image Sequence', 'PS3.3 Table C.13-5', '8, 12 (higher clamped); code default 8', 'wrong -> fixed (help cited Table C.13-3; README said 16)'),
    '--presentation-lut': ('Presentation LUT Shape (2050,0020)', 'PS3.3 Table C.11-4', 'IDENTITY, LIN OD; inverse = no shape, pixels inverted; std default none; code none', 'match (inverse: extra, documented)'),
    '--palette': ('pseudo-colour baked into RGB', 'PS3.3 Table C.13-5 (RGB only)', 'DICOMCore.PseudoColorPalette tokens', 'extra (tool feature)'),
    '--annotate': ('Text String (2030,0020) of Basic Annotation Box', 'PS3.4 H.4.4; PS3.3 Table C.13-7', 'LO; position = order given', 'match'),
    '--annotation-format': ('Annotation Display Format ID (2010,0030)', 'PS3.3 Table C.13-3', 'CS, printer Conformance Statement', 'match'),
    '--recursive': ('', '', '', 'plumbing'),
    '--dry-run': ('', '', '', 'plumbing'),
    '--retries': ('retry on connection/setup failure', '', '>=0', 'plumbing'),
    'job --job-id': ('Print Job SOP Instance UID (N-GET)', 'PS3.4 H.4.5; PS3.5 VR UI', 'UI', 'match'),
    'add-printer --name': ('local registry name', '', '', 'plumbing'),
    'add-printer --host': ('TCP address', 'PS3.8 9.1.1', '', 'plumbing'),
    'add-printer --port': ('TCP port', 'PS3.8 9.1.1 (well-known 104, registered 11112)', 'code default 11112', 'plumbing'),
    'add-printer --called-ae': ('Called AE Title', 'PS3.8 7.1.1.4; PS3.5 VR AE', '', 'plumbing'),
    'add-printer --calling-ae': ('Calling AE Title', 'PS3.8 7.1.1.3; PS3.5 VR AE', '', 'plumbing'),
    'add-printer --color': ('Meta SOP Class preference', 'PS3.6 Table A-1', 'grayscale, color', 'plumbing'),
    'add-printer --default': ('', '', '', 'plumbing'),
    'remove-printer --name': ('', '', '', 'plumbing'),
    '(smoothing-type)': ('Smoothing Type (2010,0080)', 'PS3.3 Table C.13-3 (values in Conformance Statement; CUBIC only)', 'not offered (U/U)', 'absent (optional)'),
    '(border/empty density, trim, polarity, min/max density)': ('Border Density, Empty Image Density, Trim, Polarity, Min/Max Density', 'PS3.3 Tables C.13-3 / C.13-5', 'not offered on send (U/U; offered by dicom-printscp simulate)', 'absent (optional)'),
}

CONTRACT['dicom-printscp'] = {
    '--port': ('TCP port the SCP listens on', 'PS3.8 9.1.1 (well-known 104, registered 11112)', 'code default 11113 (avoids a local SCP on 11112)', 'plumbing'),
    '--ae-title': ('Called AE Title the SCP answers as', 'PS3.8 7.1.1.4; PS3.5 VR AE', 'code default DCMPRINT', 'plumbing'),
    '--max-associations': ('', '', 'default 10', 'plumbing'),
    '--idle-timeout': ('association idle timeout', 'PS3.8 9.1.2 (ARTIM)', 'seconds; 0 disables; default 300', 'plumbing'),
    '--allow-ae': ('Calling AE Title accepted', 'PS3.8 Table 9-21 (A-ASSOCIATE-RJ reason 3)', '', 'plumbing'),
    '--deny-ae': ('Calling AE Title refused', 'PS3.8 Table 9-21', '', 'plumbing'),
    '--max-pdu': ('Maximum Length sub-item', 'PS3.8 D.1', 'bytes; default 65536', 'plumbing'),
    '--accept-color': ('Basic Color Print Management Meta SOP Class', 'PS3.4 H.3.2.2.2; PS3.6 Table A-1 (1.2.840.10008.5.1.1.18)', 'default yes', 'match (help named "Color Print Management" -> fixed)'),
    '--presentation-lut': ('Presentation LUT SOP Class N-CREATE', 'PS3.4 H.4.9, Table H.4.9.2-1; PS3.6 Table A-1 (1.2.840.10008.5.1.1.23)', 'default yes', 'match'),
    '--annotation-box': ('Basic Annotation Box SOP Class N-SET', 'PS3.4 Table H.4.4.2-1 (N-SET only); PS3.6 Table A-1 (1.2.840.10008.5.1.1.15)', 'default yes', 'wrong -> fixed (help said N-CREATE / N-SET)'),
    '--annotation-boxes-per-film': ('Referenced Basic Annotation Box Sequence (2010,0520) item count', 'PS3.4 Table H.4-6', 'default 6', 'plumbing'),
    '--push-job-events': ('Print Job N-EVENT-REPORT', 'PS3.4 H.4.5, Table H.4-14', 'Done (Event Type ID 3) only', 'wrong -> fixed (help implied several events)'),
    'serve --film-size': ('Film Size ID (2010,0050) accepted', 'PS3.3 Table C.13-3 (12 Defined Terms)', 'all 12 tokens, term accepted as alias; default all', 'match (help now names terms)'),
    'serve --medium': ('Medium Type (2000,0030) accepted', 'PS3.3 Table C.13-1 (5 Defined Terms)', 'all 5; default all', 'match'),
    '--max-image-boxes': ('image boxes per Image Display Format', 'PS3.3 Table C.13-3', 'default 64', 'plumbing'),
    '--max-image-dimension': ('', '', 'default 10000', 'plumbing'),
    '--printer-name': ('Printer Name (2110,0030)', 'PS3.3 Table C.13-9; PS3.6 Table 6-1', 'LO', 'match'),
    '--manufacturer': ('Manufacturer (0008,0070)', 'PS3.3 Table C.13-9; PS3.6 Table 6-1', 'LO', 'match'),
    '--model': ("Manufacturer's Model Name (0008,1090)", 'PS3.6 Table 6-1', 'LO', 'wrong -> fixed (help said "Manufacturer Model Name")'),
    '--serial-number': ('Device Serial Number (0018,1000)', 'PS3.6 Table 6-1', 'LO', 'match'),
    '--software-version': ('Software Versions (0018,1020)', 'PS3.6 Table 6-1', 'LO 1-n', 'wrong -> fixed (help said "Software Version")'),
    '--printer-status': ('Printer Status (2110,0010)', 'PS3.3 Table C.13-9 (Enumerated Values)', 'NORMAL, WARNING, FAILURE = normal/warning/failure; default normal', 'match'),
    '--status-info': ('Printer Status Info (2110,0020)', 'PS3.3 Table C.13-9; C.13.9.1 (108 Defined Terms)', 'free CS; empty = the status default term', 'match (Defined Terms extensible)'),
    '--dpi': ('composition resolution', '', 'default 300', 'plumbing'),
    '--density': ('P-Value to grey mapping', 'PS3.14 7 (gsdf)', 'paper, film, gsdf', 'plumbing'),
    '--margin-mm': ('', '', '', 'plumbing'),
    '--cell-spacing-mm': ('', '', '', 'plumbing'),
    '--annotations': ('draw Basic Annotation Box text', 'PS3.3 Table C.13-7', 'default yes', 'plumbing'),
    '--trim-marks': ('draw Trim (2010,0140) = YES', 'PS3.3 Table C.13-3', 'default yes; draws sheet-corner marks, not a trim box per image (D-DICOM-PRINTSCP-2)', 'plumbing'),
    '--max-pixels': ('', '', '', 'plumbing'),
    '--output': ('', '', 'png, tiff, pdf, none', 'plumbing'),
    '--output-dir': ('', '', '', 'plumbing'),
    '--name-pattern': ('', '', '', 'plumbing'),
    '--paper-queue': ('', '', '', 'plumbing'),
    '--allow-paper': ('', '', '', 'plumbing'),
    '--open': ('', '', '', 'plumbing'),
    '--config': ('', '', '', 'plumbing'),
    '--save-config': ('', '', '', 'plumbing'),
    '--max-films': ('', '', '', 'plumbing'),
    '--duration': ('', '', '', 'plumbing'),
    '--format': ('output rendering', '', 'text, json', 'plumbing'),
    '--verbose': ('', '', '', 'plumbing'),
    '--quiet': ('', '', '', 'plumbing'),
    'simulate <paths>': ('PS3.10 files', 'PS3.10 7.1', '', 'plumbing'),
    'simulate --layout': ('Image Display Format (2010,0010)', 'PS3.3 Table C.13-3', 'grid RxC (STANDARD\\C,R) + STANDARD/ROW/COL/SLIDE/SUPERSLIDE/CUSTOM forms', 'missing -> fixed (only grid tokens were accepted)'),
    'simulate --film-size': ('Film Size ID (2010,0050)', 'PS3.3 Table C.13-3', '12 terms; code default 14x17', 'match'),
    'simulate --orientation': ('Film Orientation (2010,0040)', 'PS3.3 Table C.13-3', 'PORTRAIT, LANDSCAPE', 'match'),
    'simulate --magnification': ('Magnification Type (2010,0060)', 'PS3.3 Table C.13-3', '4 terms', 'match'),
    'simulate --medium': ('Medium Type (2000,0030)', 'PS3.3 Table C.13-1', '5 terms', 'match'),
    'simulate --copies': ('Number of Copies (2000,0010)', 'PS3.3 Table C.13-1', '>=1 (clamped)', 'match'),
    'simulate --polarity': ('Polarity (2020,0020)', 'PS3.3 Table C.13-5', 'NORMAL, REVERSE; std default NORMAL = code', 'match'),
    'simulate --presentation-lut': ('Presentation LUT Shape (2050,0020)', 'PS3.3 Table C.11-4', 'IDENTITY, LIN OD; inverse rendered', 'match'),
    'simulate --trim': ('Trim (2010,0140)', 'PS3.3 Table C.13-3', 'YES/NO; code default NO', 'match'),
    'simulate --border-density': ('Border Density (2010,0100)', 'PS3.3 Table C.13-3', 'BLACK, WHITE, i hundredths of OD; code default BLACK', 'missing -> fixed (i added)'),
    'simulate --empty-density': ('Empty Image Density (2010,0110)', 'PS3.3 Table C.13-3', 'BLACK, WHITE, i; code default BLACK', 'missing -> fixed (i added)'),
    'simulate --annotate': ('Text String (2030,0020)', 'PS3.3 Table C.13-7', 'LO', 'match'),
    'simulate --annotation-format': ('Annotation Display Format ID (2010,0030)', 'PS3.3 Table C.13-3', 'CS', 'match'),
    'simulate --color': ('Basic Grayscale / Color Image Box SOP Class', 'PS3.4 H.4.3; PS3.6 Table A-1', 'grayscale, color', 'match'),
    'simulate --frame': ('', '', '', 'plumbing'),
    'simulate --all-frames': ('', '', '', 'plumbing'),
    'simulate --raw': ('', '', '', 'plumbing'),
    'simulate --window-center': ('', 'PS3.3 C.11.2', '', 'plumbing'),
    'simulate --window-width': ('', 'PS3.3 C.11.2', '', 'plumbing'),
    'simulate --bit-depth': ('Bits Stored (0028,0101)', 'PS3.3 Table C.13-5', '8, 12', 'wrong -> fixed (help said 8, 12 or 16; 16 was refused)'),
    'simulate --recursive': ('', '', '', 'plumbing'),
    'simulate --calling-ae': ('Calling AE Title recorded', 'PS3.5 VR AE', 'default SIMULATE', 'plumbing'),
}

CONTRACT['dicom-server'] = {
    'start --aet': ('Called AE Title of the SCP', 'PS3.5 Table 6.2-1 VR AE; PS3.8 9.3.2', '1-16 chars, no backslash/control; code accepts any string (not validated, D-DICOM-SERVER-9)', 'plumbing'),
    'start --port': ('TCP port', 'PS3.8 9.1.1', '104 well-known, else 11112 registered; default 11112', 'plumbing (match)'),
    'start --data-dir': ('storage directory', '-', 'path', 'plumbing'),
    'start --database': ('index backend', '-', 'sqlite|postgres|none (sqlite/postgres are in-memory / unimplemented)', 'plumbing'),
    'start --database-url': ('index connection string', '-', 'sqlite://, postgres://', 'plumbing'),
    'start --config': ('JSON ServerConfiguration file', '-', 'path', 'plumbing'),
    'start --max-connections': ('concurrent associations', '-', 'Int, default 10', 'plumbing'),
    'start --max-pdu-size': ('Maximum Length received', 'PS3.8 D.1 / PS3.7 D.3.3.1', 'UInt32, 0 = unlimited; code uses it to fragment outgoing PDUs and does not advertise it (D-DICOM-SERVER-8)', 'plumbing (behaviour finding)'),
    'start --allowed-ae': ('Calling AE Title allow list -> A-ASSOCIATE-RJ 1/1/3', 'PS3.8 Table 9-21', 'rejected-permanent / service-user / calling-AE-title-not-recognized', 'match'),
    'start --blocked-ae': ('Calling AE Title block list -> A-ASSOCIATE-RJ 1/1/3', 'PS3.8 Table 9-21', 'as --allowed-ae', 'match'),
    'start --verbose': ('logging', '-', 'flag', 'plumbing'),
    'start --tls': ('TLS', 'PS3.15 B.1 (not implemented)', 'flag; stored only', 'plumbing'),
    'status --host': ('peer host', '-', 'string; -h collides with --help', 'plumbing'),
    'status --port': ('peer port', 'PS3.8 9.1.1', 'default 11112', 'plumbing (match)'),
    'status --calling-ae': ('Calling AE Title', 'PS3.5 VR AE', '16 chars, validated by DICOMNetwork.AETitle', 'plumbing'),
    'status --called-ae': ('Called AE Title', 'PS3.5 VR AE', '16 chars, validated by DICOMNetwork.AETitle', 'plumbing'),
    'status --verbose': ('output', '-', 'flag', 'plumbing'),
    'stop --port': ('port (unused; prints SIGINT hint)', '-', 'UInt16', 'plumbing'),
    'stop --verbose': ('output', '-', 'flag', 'plumbing'),
    'stats --host': ('peer host', '-', 'string; -h collides with --help', 'plumbing'),
    'stats --port': ('peer port', 'PS3.8 9.1.1', 'default 11112', 'plumbing (match)'),
    'stats --calling-ae': ('Calling AE Title', 'PS3.5 VR AE', '16 chars', 'plumbing'),
    'stats --called-ae': ('Called AE Title', 'PS3.5 VR AE', '16 chars', 'plumbing'),
    'stats --verbose': ('output', '-', 'flag', 'plumbing'),
}

CONTRACT['dicom-gateway'] = {
    'dicom-to-hl7 <input>': ('DICOM file read', 'PS3.10 7.1', 'Part 10 file', 'plumbing'),
    'dicom-to-hl7 --output': ('HL7 output path', '-', 'path', 'plumbing'),
    'dicom-to-hl7 --message-type': ('HL7 v2 message type (not NEMA)', 'HL7 v2.5', 'ADT, ORM, ORU', 'plumbing'),
    'dicom-to-hl7 --event-type': ('HL7 ADT trigger event (not NEMA)', 'HL7 v2.5', 'A01..; was sent as ADT^AA01, fixed', 'plumbing (fixed)'),
    'dicom-to-hl7 --verbose': ('output', '-', 'flag', 'plumbing'),
    'hl7-to-dicom <input>': ('HL7 v2 message (not NEMA)', 'HL7 v2.5', 'ER7 text', 'plumbing'),
    'hl7-to-dicom --output': ('DICOM output; PN/DA/TM/CS/UI values', 'PS3.5 Table 6.2-1, 6.2.1, 9.1; PS3.3 Table C.7-1', "PN 5 components, DA YYYYMMDD, TM HH[MM[SS[.F]]], Patient's Sex M/F/O, UID syntax, SH 16 / LO 64", 'wrong -> fixed'),
    'hl7-to-dicom --template': ('template DICOM file', 'PS3.10 7.1', 'path', 'plumbing'),
    'hl7-to-dicom --verbose': ('output', '-', 'flag', 'plumbing'),
    'dicom-to-fhir <input>': ('DICOM file read; PN first component group', 'PS3.5 6.2.1', 'Part 10 file', 'wrong -> fixed'),
    'dicom-to-fhir --output': ('FHIR JSON path', '-', 'path', 'plumbing'),
    'dicom-to-fhir --resource': ('FHIR resource type (not NEMA); modality system URI', 'PS3.16 Table 8-1 (DCM FHIR URI)', 'ImagingStudy, Patient, Practitioner, DiagnosticReport; http://dicom.nema.org/resources/ontology/DCM', 'match'),
    'dicom-to-fhir --pretty': ('JSON formatting', '-', 'flag', 'plumbing'),
    'dicom-to-fhir --verbose': ('output', '-', 'flag', 'plumbing'),
    'fhir-to-dicom <input>': ('FHIR JSON (not NEMA)', 'FHIR R4', 'ImagingStudy, Patient', 'plumbing'),
    'fhir-to-dicom --output': ('DICOM output; PN/DA/TM/CS/UI values', 'PS3.5 Table 6.2-1, 9.1; PS3.3 Table C.7-1', 'as hl7-to-dicom --output', 'wrong -> fixed'),
    'fhir-to-dicom --template': ('template DICOM file', 'PS3.10 7.1', 'path', 'plumbing'),
    'fhir-to-dicom --verbose': ('output', '-', 'flag', 'plumbing'),
    'batch <conversion-type>': ('conversion selector', '-', 'dicom-to-hl7, dicom-to-fhir', 'plumbing'),
    'batch <input-pattern>': ('input glob', '-', 'path pattern', 'plumbing'),
    'batch --output': ('output directory', '-', 'path', 'plumbing'),
    'batch --type': ('message/resource type (not NEMA)', '-', 'ADT (only ADT used for hl7), FHIR resource types', 'plumbing'),
    'batch --verbose': ('output', '-', 'flag', 'plumbing'),
    'listen --protocol': ('listener protocol (not NEMA)', '-', 'hl7', 'plumbing'),
    'listen --port': ('HL7 port', '-', 'default 2575 (HL7 MLLP convention)', 'plumbing'),
    'listen --forward': ('PACS destination for converted messages', 'PS3.8 9.1.1', 'pacs://host:port; C-STORE not implemented (stub)', 'plumbing (stub)'),
    'listen --message-types': ('HL7 message filter', '-', 'comma list', 'plumbing'),
    'listen --verbose': ('output', '-', 'flag', 'plumbing'),
    'forward --listen-port': ('DICOM listening port', 'PS3.8 9.1.1', 'default 11112 registered port; no PS3.8 UL implemented (D-DICOM-GATEWAY-2)', 'plumbing (match default)'),
    'forward --forward-hl7': ('HL7 destination', '-', 'hl7://host:port', 'plumbing'),
    'forward --forward-fhir': ('FHIR destination', '-', 'URL', 'plumbing'),
    'forward --message-type': ('HL7 message type', '-', 'ADT, ORM, ORU', 'plumbing'),
    'forward --verbose': ('output', '-', 'flag', 'plumbing'),
}

CONTRACT['dicom-wado'] = {
    # retrieve (WADO-RS PS3.18 10.4; WADO-URI PS3.18 Section 9)
    'retrieve <base-url>': ('Studies Service base URI / URI service endpoint', 'PS3.18 Table 10.1-1; 9.1', 'http(s) URL; /rs rewritten to /wado with --uri (dcm4chee)', 'plumbing'),
    'retrieve --study': ('Study Instance UID: {study} path segment / studyUID', 'PS3.18 Tables 10.4.1-1, 9.1.2-1', 'UID; required (M in 9.1.2-1)', 'match'),
    'retrieve --series': ('Series Instance UID: {series} / seriesUID', 'PS3.18 Tables 10.4.1-1, 9.1.2-1', 'UID; required with --uri', 'match'),
    'retrieve --instance': ('SOP Instance UID: {instance} / objectUID', 'PS3.18 Tables 10.4.1-1, 9.1.2-1', 'UID; required with --uri', 'match'),
    'retrieve --frames': ('{frameList} (RS) / frameNumber (URI)', 'PS3.18 Table 10.4.1.6-1; 9.5.1.2.1', 'RS: comma list of positive ints; URI: one positive int', 'wrong (URI: 0/text sent or dropped; fixed 39da529)'),
    'retrieve --uri': ('URI service (WADO-URI), requestType=WADO', 'PS3.18 9.1.2.1.1', '"WADO"', 'match'),
    'retrieve --content-type': ('contentType', 'PS3.18 9.1.2.2.1; Table 8.7.4-1', 'application/dicom or a Rendered Media Type (15 in 8.7.4-1); tool: 7', 'wrong (unknown value silently fetched application/dicom; fixed 39da529)'),
    'retrieve --transfer-syntax': ('transferSyntax', 'PS3.18 9.4.1.2.3, Table 9.4.1-1', 'one Transfer Syntax UID', 'missing (added 39da529)'),
    'retrieve --anonymize': ('anonymize=yes', 'PS3.18 9.4.1.2.1, Table 9.4.1-1', '"yes"', 'missing (added 39da529)'),
    'retrieve --rows': ('rows', 'PS3.18 9.5.1.2.4.1, Table 9.5.1-1', 'positive integer', 'missing (added 39da529)'),
    'retrieve --columns': ('columns', 'PS3.18 9.5.1.2.4.2, Table 9.5.1-1', 'positive integer', 'missing (added 39da529)'),
    '(retrieve: charset, annotation, imageAnnotation, imageQuality, region, windowCenter, windowWidth, presentationUID, presentationSeriesUID)': ('optional WADO-URI parameters', 'PS3.18 Tables 9.1.2-2, 9.4.1-1, 9.5.1-1', 'O; not in WADOURIClient.buildURL', 'missing (optional)'),
    'retrieve --metadata': ('Metadata resources', 'PS3.18 Table 10.4.1-2', 'study / series / instance /metadata', 'match'),
    'retrieve --rendered': ('Rendered resources', 'PS3.18 Table 10.4.1-3; 8.7.4-1 (image/jpeg default)', 'instance /rendered; saved as .jpg', 'match'),
    'retrieve --thumbnail': ('Thumbnail resources', 'PS3.18 Table 10.4.1-4', 'study / series / instance /thumbnail', 'match'),
    'retrieve -f, --format': ('metadata media type', 'PS3.18 Table 8.7.3-3; Annex F (JSON); PS3.19 Native DICOM Model (XML)', 'json, xml; default json', 'match'),
    'retrieve -o, --output': ('', '', 'directory', 'plumbing'),
    'retrieve --token': ('HTTP Authorization bearer token', 'PS3.18 8.4 (header fields; RFC 6750)', '', 'plumbing'),
    'retrieve --timeout': ('HTTP request timeout', '', 'seconds; default 60', 'plumbing (was ignored; fixed 39da529)'),
    'retrieve --verbose': ('', '', '', 'plumbing'),
    # query (QIDO-RS PS3.18 10.6)
    'query <base-url>': ('Studies Service base URI', 'PS3.18 Table 10.1-1', 'http(s) URL', 'plumbing'),
    'query --level': ('Search resource level', 'PS3.18 Tables 10.6.1-1, 10.6.1-5', 'study, series, instance; default study', 'match'),
    'query --patient-name': ("Patient's Name (0010,0010)", 'PS3.18 Table 10.6.1-5; 8.3.4.1', 'PN, * ? wild card', 'match'),
    'query --patient-id': ('Patient ID (0010,0020)', 'PS3.18 Table 10.6.1-5', 'LO', 'match'),
    'query --study-date': ('Study Date (0008,0020)', 'PS3.18 Table 10.6.1-5; PS3.4 C.2.2.2.5', 'DA or DA-DA range', 'match'),
    'query --study': ('Study Instance UID (0020,000D); {study} of series/instance search', 'PS3.18 Tables 10.6.1-1, 10.6.1-5', 'UID', 'match'),
    'query --series': ('Series Instance UID (0020,000E)', 'PS3.18 Table 10.6.1-5', 'UID', 'match'),
    'query --accession-number': ('Accession Number (0008,0050)', 'PS3.18 Table 10.6.1-5', 'SH', 'match'),
    'query --modality': ('Modalities In Study (0008,0061) at study/instance level; Modality (0008,0060) at series level', 'PS3.18 Table 10.6.1-5', 'CS Defined Terms (shared ModalityOptionValidator)', 'match'),
    'query --strict-modality': ('reject non-Defined-Term Modality', 'PS3.3 C.7.3.1.1.1', '', 'match'),
    'query --study-description': ('Study Description (0008,1030)', 'not in PS3.18 Table 10.6.1-5 (server-optional key)', 'LO', 'extra'),
    'query --pps-start-date': ('Performed Procedure Step Start Date (0040,0244), series', 'PS3.18 Table 10.6.1-5', 'DA / range', 'match'),
    'query --pps-start-time': ('Performed Procedure Step Start Time (0040,0245), series', 'PS3.18 Table 10.6.1-5', 'TM / range', 'match'),
    'query --sps-id': ('>Scheduled Procedure Step ID (0040,0275.0040,0009), series', 'PS3.18 Table 10.6.1-5', 'SH', 'match'),
    'query --requested-procedure-id': ('>Requested Procedure ID (0040,0275.0040,1001), series', 'PS3.18 Table 10.6.1-5', 'SH', 'match'),
    'query --limit': ('limit', 'PS3.18 Table 8.3.4-1; 8.3.4.4', 'uint; no standard default (code 100)', 'wrong (negative accepted; fixed 39da529)'),
    'query --offset': ('offset', 'PS3.18 Table 8.3.4-1; 8.3.4.4', 'uint; default 0', 'wrong (negative accepted; fixed 39da529)'),
    'query --fuzzy-matching': ('fuzzymatching=true', 'PS3.18 Table 8.3.4-1; 8.3.4.2', 'true/false', 'missing (added 39da529)'),
    '(query: includefield, emptyvaluematching, multiplevaluematching)': ('QIDO query parameters', 'PS3.18 Table 8.3.4-1; 8.3.4.3, 8.3.4.5, 8.3.4.6', 'O for user agent', 'missing (optional; includefield useful only with P-QUERY-JSON)'),
    '(query keys: Study Time, Referring Physician Name, Study ID, Series Number, SOP Class UID, SOP Instance UID, Instance Number)': ('Required Matching Attributes the origin server supports', 'PS3.18 Table 10.6.1-5', '7 of 20 rows not settable', 'missing (optional for the user agent)'),
    'query -f, --format': ('result rendering', 'PS3.18 Annex F (not followed)', 'table, json (keyword-keyed summary), csv', 'extra (P-QUERY-JSON)'),
    'query --token': ('HTTP Authorization bearer token', 'PS3.18 8.4', '', 'plumbing'),
    'query --verbose': ('', '', '', 'plumbing'),
    # store (STOW-RS PS3.18 10.5)
    'store <base-url>': ('Studies Service base URI', 'PS3.18 Table 10.5.1-1', 'http(s) URL', 'plumbing'),
    'store <files>': ('PS3.10 files sent as application/dicom parts', 'PS3.18 10.5.1; Table 8.7.3-2', 'paths', 'plumbing'),
    'store --study': ('/studies/{study} target', 'PS3.18 Table 10.5.1-1', 'UID', 'match'),
    'store --input': ('', '', 'file list', 'plumbing'),
    'store --batch': ('instances per request', '', '>= 1; default 10', 'plumbing'),
    'store --continue-on-error': ('', 'PS3.18 Table 10.5.3-1 (202/4xx = not all stored)', '', 'plumbing (exit 0 on failures; fixed 39da529: exit 1)'),
    'store --token': ('HTTP Authorization bearer token', 'PS3.18 8.4', '', 'plumbing'),
    'store --verbose': ('', '', '', 'plumbing'),
    # ups (UPS-RS PS3.18 11)
    'ups <base-url>': ('Worklist Service base URI', 'PS3.18 Table 11.1.1-1', 'http(s) URL', 'plumbing'),
    'ups --search': ('Search Transaction GET /workitems', 'PS3.18 11.9; Table 11.3-1', '', 'match'),
    'ups --get': ('Retrieve Workitem GET /workitems/{workitem}', 'PS3.18 11.5; Table 11.3-1', 'UID', 'match'),
    'ups --create': ('Create Workitem POST /workitems from DICOM JSON', 'PS3.18 11.4; Table 11.3-1', 'JSON file', 'match'),
    'ups --create-workitem': ('Create Workitem from options', 'PS3.18 11.4; PS3.4 Table CC.2.5-3', '', 'match'),
    'ups --update': ('Change Workitem State PUT /workitems/{workitem}/state', 'PS3.18 11.7; Table 11.3-1', 'UID (name suggests Update 11.6: P-WADO-UPS-UPDATE)', 'match'),
    'ups --subscribe': ('Subscribe POST .../subscribers/{subscriber}', 'PS3.18 11.10; Table 11.1.1-1', 'workitem or Worklist (1.2.840.10008.5.1.4.34.5)', 'match'),
    'ups --unsubscribe': ('Unsubscribe DELETE .../subscribers/{subscriber}', 'PS3.18 11.11', '', 'match'),
    'ups --aet': ('{subscriber} AE Title / requester', 'PS3.18 11.10.1, Table 11.7.2.1-1; PS3.5 VR AE', 'AE; sent as path segment (dcm4chee), not ?requester=', 'match'),
    'ups --state': ('Procedure Step State (0074,1000) of Change State', 'PS3.18 11.7.1.4; PS3.3 Table C.30.1-1', 'IN PROGRESS, COMPLETED, CANCELED', 'wrong ("IN PROGRESS" rejected; fixed 39da529; SCHEDULED warns, P-WADO-UPS-STATE)'),
    'ups --transaction-uid': ('Transaction UID (0008,1195)', 'PS3.18 11.7.1.4', 'UI; generated for IN PROGRESS, required for COMPLETED/CANCELED', 'match'),
    'ups --filter-state': ('Procedure Step State (0074,1000) matching key', 'PS3.3 Table C.30.1-1', 'SCHEDULED, IN PROGRESS, COMPLETED, CANCELED', 'wrong ("IN PROGRESS" rejected; fixed 39da529)'),
    'ups --scheduled-station': ('Scheduled Station Name Code Sequence (0040,4025) key', 'PS3.4 Table CC.2.5-3', '', 'match'),
    'ups --workitem-uid': ('Workitem SOP Instance UID {workitem}', 'PS3.18 Table 11.1.1-1', 'UID; generated under 1.2.826.0.1.3680043.8.498', 'match'),
    'ups --label': ('Procedure Step Label (0074,1204)', 'PS3.3 Table C.30.2-1', 'LO; required for --create-workitem', 'match'),
    'ups --patient-name': ("Patient's Name (0010,0010)", 'PS3.4 Table CC.2.5-3', 'PN', 'match'),
    'ups --patient-id': ('Patient ID (0010,0020)', 'PS3.4 Table CC.2.5-3', 'LO', 'match'),
    'ups --priority': ('Scheduled Procedure Step Priority (0074,1200)', 'PS3.3 Table C.30.2-1', 'HIGH, MEDIUM, LOW; STAT -> HIGH; default MEDIUM', 'match (help named STAT as a value; fixed 39da529)'),
    'ups --patient-birth-date': ("Patient's Birth Date (0010,0030)", 'PS3.5 VR DA', 'YYYYMMDD', 'match'),
    'ups --patient-sex': ("Patient's Sex (0010,0040)", 'PS3.3 Table C.7-1', 'M, F, O', 'match'),
    'ups --study-uid': ('Study Instance UID (0020,000D)', 'PS3.4 Table CC.2.5-3', 'UID', 'match'),
    'ups --accession-number': ('Accession Number (0008,0050)', 'PS3.4 Table CC.2.5-3', 'SH', 'match'),
    'ups --referring-physician': ("Referring Physician's Name (0008,0090)", 'PS3.6 Table 6-1', 'PN', 'match'),
    'ups --procedure-id': ('Requested Procedure ID (0040,1001)', 'PS3.6 Table 6-1', 'SH', 'match'),
    'ups --step-id': ('Scheduled Procedure Step ID (0040,0009)', 'PS3.6 Table 6-1', 'SH', 'match'),
    'ups --worklist-label': ('Worklist Label (0074,1202)', 'PS3.3 Table C.30.2-1', 'LO', 'match'),
    'ups --comments': ('Comments on the Scheduled Procedure Step (0040,0400)', 'PS3.6 Table 6-1', 'LT', 'match'),
    'ups --scheduled-start': ('Scheduled Procedure Step Start DateTime (0040,4005)', 'PS3.5 VR DT', 'ISO 8601 input -> DT', 'match'),
    'ups --expected-completion': ('Expected Completion DateTime (0040,4011)', 'PS3.5 VR DT', 'ISO 8601 input -> DT', 'match'),
    'ups --station-name': ('Scheduled Station Name Code Sequence (0040,4025) item', 'PS3.3 8.2 (designator "L" = local)', 'code value = meaning = name, scheme L', 'match'),
    'ups --performer-name': ("Human Performer's Name (0040,4037) in (0040,4034)", 'PS3.6 Table 6-1', 'PN', 'match'),
    'ups --performer-organization': ("Human Performer's Organization (0040,4036)", 'PS3.6 Table 6-1', 'LO', 'match'),
    'ups --admission-id': ('Admission ID (0038,0010)', 'PS3.6 Table 6-1', 'LO', 'match'),
    '(ups: Update Workitem, Request Cancellation)': ('UPS-RS transactions', 'PS3.18 11.6, 11.8; Table 11.3-1', 'DICOMwebClient has both', 'missing (optional)'),
    'ups -f, --format': ('result rendering', 'PS3.18 Annex F (not followed)', 'table, json (camelCase summary), csv; help omitted csv (fixed)', 'extra (P-QUERY-JSON)'),
    'ups --token': ('HTTP Authorization bearer token', 'PS3.18 8.4', '', 'plumbing'),
    'ups --verbose': ('', '', '', 'plumbing'),
}

CONTRACT['dicom-jpip'] = {
    'fetch <server-url>': ('JPIP server (ISO/IEC 15444-9)', 'PS3.5 8.4.1 (HTTP/HTTPS transport)', 'http(s) URL', 'plumbing'),
    'fetch --image': ('JPIP target', 'ISO/IEC 15444-9 (out of scope)', '', 'plumbing'),
    'fetch --layers': ('JPIP quality layers', 'ISO/IEC 15444-9 (out of scope)', '', 'plumbing'),
    'fetch --level': ('JPIP resolution level', 'ISO/IEC 15444-9 (out of scope)', '', 'plumbing'),
    'fetch --region': ('JPIP region', 'ISO/IEC 15444-9 (out of scope)', 'x,y,w,h', 'plumbing'),
    'fetch -o, --output': ('', '', '', 'plumbing'),
    'fetch -v, --verbose': ('', '', '', 'plumbing'),
    'uri <input>': ('PS3.10 file with a JPIP Referenced Transfer Syntax; prints Pixel Data Provider URL (0028,7FE0)', 'PS3.6 Table A-1 (4 JPIP UIDs); PS3.5 8.4.1, A.6, A.7, A.11, A.12', '.4.94, .4.95, .4.204, .4.205', 'wrong (.4.204/.4.205 refused; fixed 827f021)'),
    'uri --json': ('summary JSON (file, transferSyntaxUID, isDeflated, jpipURI)', '', 'tool keys', 'plumbing'),
    'serve -p, --port': ('JPIP server port', 'ISO/IEC 15444-9; no DICOM default', 'default 8080', 'plumbing'),
    'serve -d, --directory': ('', '', '*.dcm files', 'plumbing'),
    'serve --max-clients': ('', '', 'default 16', 'plumbing'),
    'serve --client-bandwidth': ('', '', 'bytes/s; 0 = unlimited', 'plumbing'),
    'serve -v, --verbose': ('', '', '', 'plumbing'),
    'info <target>': ('file or JPIP server URL', 'PS3.5 8.4.1', '', 'plumbing'),
    'info --list-syntaxes': ('JPIP Referenced Transfer Syntaxes', 'PS3.6 Table A-1', '4 UIDs with A-1 names', 'wrong (2 of 4 listed, "Pixel Data contains a JPIP URI", A.8 cited; fixed 827f021)'),
    'info --json': ('summary JSON (file, transferSyntaxUID, isJPIP, jpipURI)', '', 'tool keys', 'plumbing'),
}

CONTRACT['dicom-cloud'] = {
    '<source>': ('local path or cloud URL', '', 's3:// gs:// azure://', 'plumbing'),
    '<destination>': ('cloud URL or local path', '', '', 'plumbing'),
    '<cloud-url>': ('cloud URL', '', '', 'plumbing'),
    '<local-path>': ('local directory', '', '', 'plumbing'),
    '-r, --recursive': ('', '', '', 'plumbing'),
    '--tags': ('object metadata key=value', 'none (keys are free text; e.g. PatientID is a PS3.6 keyword but not written as a DICOM attribute)', '', 'plumbing'),
    '--encrypt': ('storage encryption', 'none (not PS3.15)', 'none, server-side, client-side', 'plumbing'),
    '--multipart': ('', '', '', 'plumbing'),
    '--parallel': ('', '', 'default 4', 'plumbing'),
    '--resume': ('', '', '', 'plumbing'),
    '--endpoint': ('S3-compatible endpoint', '', '', 'plumbing'),
    '--region': ('cloud region', '', '', 'plumbing'),
    '--details': ('', '', '', 'plumbing'),
    '--force': ('', '', '', 'plumbing'),
    '--bidirectional': ('sync direction', '', 'default upload only (help prose fixed b7a11a4)', 'plumbing'),
    '--delete': ('', '', '', 'plumbing'),
    '--source-region': ('', '', '', 'plumbing'),
    '--dest-region': ('', '', '', 'plumbing'),
    '-v, --verbose': ('', '', '', 'plumbing'),
}
