#!/usr/bin/env python3
"""
Generate the DICOM Data Element Dictionary resource.

Produces Sources/DICOMDictionary/Resources/DataElementDictionary.txt, a
pipe-delimited file read at runtime by DataElementDictionary.swift:

    GGGG|EEEE|Name|Keyword|VR[/VR...]|VM|Retired

  - Multi-VR attributes keep every VR, primary first ("US/OW", "OB/OW").
  - Repeating groups (50xx Curve, 60xx Overlay) are emitted once at their
    base group (5000, 6000); the Swift loader normalises any even group in
    the range to the base before lookup.
  - Retired is "R" or empty. Retired elements are still emitted because
    they appear in real-world files and must be nameable.

The Swift loader (DataElementDictionary.swift) is hand-maintained and NOT
regenerated by this script.
"""

import os
import sys

try:
    from pydicom.datadict import DicomDictionary, RepeatersDictionary
except ImportError:
    print("Error: pydicom is required. Install with: pip3 install pydicom", file=sys.stderr)
    sys.exit(1)

# The Swift VR enum (DICOMCore/VR.swift). Anything else is dropped.
SWIFT_VRS = {
    "AE", "AS", "AT", "CS", "DA", "DS", "DT", "FL", "FD", "IS", "LO", "LT",
    "OB", "OD", "OF", "OL", "OV", "OW", "PN", "SH", "SL", "SQ", "SS", "ST",
    "SV", "TM", "UC", "UI", "UL", "UN", "UR", "US", "UT", "UV",
}

# Repeating-group masks we materialise, mapped to their base group.
REPEATING_BASES = {"50xx": 0x5000, "60xx": 0x6000}


def swift_vr_field(vr_str):
    """'US or SS' -> 'US/SS'; returns None if no VR is representable."""
    parts = [p.strip() for p in vr_str.split(" or ")]
    parts = [p for p in parts if p in SWIFT_VRS]
    return "/".join(parts) if parts else None


def row(group, element, vr_str, vm, name, retired_str, keyword):
    vr = swift_vr_field(vr_str)
    if vr is None:
        return None
    kw = keyword or name.replace(" ", "") or "Unknown"
    retired = "R" if retired_str else ""
    return f"{group:04X}|{element:04X}|{name}|{kw}|{vr}|{vm}|{retired}"


def main():
    base_dir = "Sources/DICOMDictionary"
    resource_dir = f"{base_dir}/Resources"
    os.makedirs(resource_dir, exist_ok=True)

    rows = {}

    for tag_int, (vr_str, vm, name, retired_str, keyword) in DicomDictionary.items():
        group = (tag_int >> 16) & 0xFFFF
        element = tag_int & 0xFFFF
        r = row(group, element, vr_str, vm, name, retired_str, keyword)
        if r:
            rows[(group, element)] = r

    for mask, (vr_str, vm, name, retired_str, keyword) in RepeatersDictionary.items():
        prefix = mask[:4]
        if prefix not in REPEATING_BASES:
            continue
        group = REPEATING_BASES[prefix]
        element = int(mask[4:], 16)
        r = row(group, element, vr_str, vm, name, retired_str, keyword)
        if r:
            rows[(group, element)] = r

    lines = [rows[k] for k in sorted(rows)]

    resource_path = f"{resource_dir}/DataElementDictionary.txt"
    with open(resource_path, "w") as f:
        f.write("\n".join(lines))
        f.write("\n")
    print(f"Generated {resource_path} ({len(lines)} entries)")


if __name__ == "__main__":
    main()
