#!/usr/bin/env python3
"""Generate the Basic Application Level Confidentiality Profile rules of DICOMKit from the
frozen DICOM DocBook: every row of PS3.15 Table E.1-1.

Usage:
    python3 Scripts/nema_docbook.py fetch 2026a 15 --out DIR
    python3 Scripts/generate_confidentiality_profile.py --nema DIR [--check]

Writes Sources/DICOMKit/Anonymization/ConfidentialityProfileTableE11.swift: one entry per
row with a single tag — its Basic Profile action and the action of every option column
(Retain UIDs, Device Identity, Institution Identity, Patient Characteristics, Longitudinal
Full / Modified Dates, Clean Descriptors, Clean Structured Content, Clean Graphics) — plus
the four pattern rows (curve data, overlay data and comments, private groups), which the
engine applies by group. With --check it compares the existing file instead and exits 1 on
any difference, so the table can be verified without being rewritten.

This is the "data too large to maintain by hand" step of the verification method in
DICOMCORE_STANDARD_IMPLEMENTATION.md (D69, DICOMKIT_STANDARD_IMPLEMENTATION.md).
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import nema_docbook as nd  # noqa: E402

OUT = os.path.join(ROOT, 'Sources', 'DICOMKit', 'Anonymization', 'ConfidentialityProfileTableE11.swift')
# Table E.1-1 option columns, in table order, and the field each fills.
OPTION_FIELDS = [
    ('Rtn. Safe Priv. Opt.', None),            # private attributes: not modelled (all removed)
    ('Rtn. UIDs Opt.', 'uids'),
    ('Rtn. Dev. Id. Opt.', 'device'),
    ('Rtn. Inst. Id. Opt.', 'institution'),
    ('Rtn. Pat. Chars. Opt.', 'patient'),
    ('Rtn. Long. Full Dates Opt.', 'fullDates'),
    ('Rtn. Long. Modif. Dates Opt.', 'modifiedDates'),
    ('Clean Desc. Opt.', 'cleanDescriptors'),
    ('Clean Struct. Cont. Opt.', 'cleanStructuredContent'),
    ('Clean Graph. Opt.', 'cleanGraphics'),
]
PATTERNS = {'(50xx,xxxx)', '(60xx,4000)', '(60xx,3000)', '(gggg,eeee) where gggg is odd'}


def rows(p15):
    table = p15.table('E.1-1')
    header = list(p15.rows(table, header=True))[0]
    expected = ['Attribute Name', 'Tag', None, None, 'Basic Prof.'] + [c for c, _ in OPTION_FIELDS]
    for i, name in enumerate(expected):
        if name is not None and header[i] != name:
            sys.exit(f'Table E.1-1 column {i} is {header[i]!r}, expected {name!r}; re-read the table')
    out, patterns = [], []
    for row in p15.rows(table):
        if len(row) < 15:
            continue
        tag = row[1].strip()
        if tag in PATTERNS:
            patterns.append((tag, row[0], row[4].replace(' ', '')))
            continue
        m = re.fullmatch(r'\(([0-9A-Fa-f]{4}),([0-9A-Fa-f]{4})\)', tag)
        if not m:
            sys.exit(f'Table E.1-1 row {row[0]!r}: tag {tag!r} is neither a tag nor a known pattern')
        options = {field: row[5 + i].strip() for i, (_, field) in enumerate(OPTION_FIELDS)
                   if field and row[5 + i].strip()}
        out.append(((m.group(1) + m.group(2)).upper(), row[0], row[4].replace(' ', ''), options))
    return out, patterns


def swift(rows_, patterns, subtitle):
    lines = [
        '// ConfidentialityProfileTableE11.swift',
        '// DICOMKit',
        '//',
        f'// GENERATED by Scripts/generate_confidentiality_profile.py from {subtitle},',
        f'// Table E.1-1 ({len(rows_)} single-tag rows; the {len(patterns)} pattern rows are applied by group',
        '// in ConfidentialityEngine). Do not hand-edit: fix the generator and regenerate.',
        '//',
        f'// NEMA-verified: 2026a, checked 2026-09-30 — every single-tag row of PS3.15 2026a Table E.1-1 '
        f'({len(rows_)}), with its Basic Profile action and all option columns, generated from the DocBook '
        '(D69); `generate_confidentiality_profile.py --check` re-verifies it.',
        '',
        'extension ConfidentialityProfile {',
        '    /// One row of PS3.15 Table E.1-1: the Basic Profile action and, per option, the',
        '    /// action the option substitutes ("K" keep, "C" clean), as the table writes them.',
        '    struct E11Row: Sendable, Equatable {',
        '        let basic: String',
        '        var uids: String? = nil',
        '        var device: String? = nil',
        '        var institution: String? = nil',
        '        var patient: String? = nil',
        '        var fullDates: String? = nil',
        '        var modifiedDates: String? = nil',
        '        var cleanDescriptors: String? = nil',
        '        var cleanStructuredContent: String? = nil',
        '        var cleanGraphics: String? = nil',
        '    }',
        '',
        '    /// Table E.1-1, keyed by (group << 16 | element).',
        '    static let tableE11: [UInt32: E11Row] = [',
    ]
    for tag, name, basic, options in sorted(rows_):
        args = [f'basic: "{basic}"'] + [f'{f}: "{v}"' for f in
                                          ('uids', 'device', 'institution', 'patient', 'fullDates', 'modifiedDates',
                                           'cleanDescriptors', 'cleanStructuredContent', 'cleanGraphics')
                                          if (v := options.get(f))]
        lines.append(f'        0x{tag}: E11Row({", ".join(args)}),  // {name}')
    lines += ['    ]', '}', '']
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--nema', required=True)
    ap.add_argument('--edition', default='2026a')
    ap.add_argument('--check', action='store_true', help='compare with the existing file; exit 1 on a difference')
    args = ap.parse_args()
    path = os.path.join(args.nema, f'part15_{args.edition}.xml')
    p15 = nd.Part(path)
    if args.edition not in p15.subtitle:
        sys.exit(f'{path}: subtitle {p15.subtitle!r} does not name {args.edition}')
    rows_, patterns = rows(p15)
    if len(patterns) != len(PATTERNS):
        sys.exit(f'expected the {len(PATTERNS)} pattern rows, found {[p[0] for p in patterns]}')
    text = swift(rows_, patterns, p15.subtitle)
    if args.check:
        current = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if current != text:
            print(f'{OUT} differs from PS3.15 {args.edition} Table E.1-1; regenerate')
            sys.exit(1)
        print(f'ok: {len(rows_)} rows and {len(patterns)} patterns of Table E.1-1 match {os.path.relpath(OUT, ROOT)}')
        return
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(text)
    print(f'wrote {os.path.relpath(OUT, ROOT)}: {len(rows_)} rows; patterns {", ".join(p[0] for p in patterns)}')


if __name__ == '__main__':
    main()
